### ISSUE TITLE
Arzt löschen

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#101]
Diesen Arzt bitte löschen:

https://ch.oddb.org/de/gcc/doctor/oid/20256

bitte im Issue die bin/admin Befehle festhalten.

Dieser Arzt ist der gleiche: https://ch.oddb.org/de/gcc/suggest_address/doctor/7601000105677/address/0/zone/doctors und sollte das Staatsexamenjahr 1991 erhalten.

**Comment by zdavatz** [comment]
Meine alte Adresse (bis Ende 2017/Anfang 2018, daher bitte löschen):

Peter Baumgartner, Dr.med., Oberburgstrasse 67, 3400 Burgdorf, Tel. 034 420 7000

E-Mail bisher  praxis-baumgartner@bluewin.ch

Meine aktuelle Praxisadresse:

Peter Baumgartner, Dr. med., Seestrasse 2, 3700 Spiez, Tel. 033 655 0830,

E-Mail neu  pba@hin.ch

**Comment by ngiger** [comment]
This can be done using the following steps via bin/admin

<pre>
$oid2delete = 20256
$newGlnId=7601000105677
$doctor2delete = doctors.values.find{|x| x.oid == $oid2delete}
$doctor2delete.name
$doctor2delete.firstname
$doctor2delete.exam
$doctor2correct = doctor_by_gln($newGlnId)
$doctor2correct.name
$doctor2correct.firstname
$doctor2correct.exam = 1991
$doctor2correct.odba_store
doctors.size
doctors.delete($oid2delete)
doctors.size
$doctor2delete.odba_delete
doctors.odba_store`
</pre>

Ich komme nicht mehr via ssh auf thinpower. Kannst Du dort beim user ywesee meinen Public Key (neu) hinzufügen. Der wäre

`ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJY7+iMHzZ4v7rfVdmpkMFzxwWwetpj9F/At/bo0OM1i Niklaus Giger Dez 2019`

**Comment by zdavatz** [comment]
Ist jetzt hinterlegt. Deinen alten Key habe ich gelöscht.

**Comment by zdavatz** [comment]
wie startet man `bin/admin`?

**Comment by ngiger** [comment]
Auf thinpower gibst Du folgende Befehle ein:
<pre>
cd /var/www/oddb.org
bin/admin
</pre>

**Comment by zdavatz** [comment]
Danke @ngiger. Wird dann die korrekte Ruby-Version verwendet?

**Comment by zdavatz** [comment]
@ngiger hat das Löschen auf Thinpower geklappt?

**Comment by zdavatz** [comment]
```
ch.oddb> doctor2correct.firstname
-> undefined method `doctor2correct' for #<OddbPrevalence:0x00007f0b6a2d0f60>
Did you mean?  doctor_count
```

**Comment by ngiger** [comment]
In bin/admin gibt es nur globale Variablen, deshalb $doctor2correct und nicht doctor2correct verwenden!

**Comment by zdavatz** [comment]
Danke!
