### ISSUE TITLE
Ruby 2.5.0 vs Ruby 2.7.1 hexdump issue

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#104]
Ruby 2.5.0
```
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
/tmp> irb
irb(main):001:0> require 'date'
=> true
irb(main):002:0> hexdump = "0408553a09446174655b0b690069006902c0a8553a0d526174696f6e616c5b076c2b0800001a71180269029dff6900660c32323939313631"
=> "0408553a09446174655b0b690069006902c0a8553a0d526174696f6e616c5b076c2b0800001a71180269029dff6900660c32323939313631"
irb(main):003:0> Marshal.load(hexdump)
Traceback (most recent call last):
        3: from /home/zeno/.rbenv/versions/2.5.0/bin/irb:11:in `<main>'
        2: from (irb):3
        1: from (irb):3:in `load'
TypeError (incompatible marshal file format (can't be read)
        format version 4.8 required; 48.52 given)
irb(main):004:0> exit
```
and for 2.7.1
```
/tmp> rbenv local 2.7.1
/tmp> ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
/tmp> irb
irb(main):001:0> require 'date'
=> true
irb(main):002:0> hexdump = "0408553a09446174655b0b690069006902c0a8553a0d526174696f6e616c5b076c2b0800001a71180269029dff6900660c32323939313631"
irb(main):003:0> Marshal.load(hexdump)
Traceback (most recent call last):
        5: from /home/zeno/.rbenv/versions/2.7.1/bin/irb:23:in `<main>'
        4: from /home/zeno/.rbenv/versions/2.7.1/bin/irb:23:in `load'
        3: from /home/zeno/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        2: from (irb):3
        1: from (irb):3:in `load'
TypeError (incompatible marshal file format (can't be read))
        format version 4.8 required; 48.52 given
irb(main):004:0>
```

**Comment by ngiger** [comment]
Example is not correct, as ODBA::Marshall.load first converts the hexdump into a binary.

Correct example is:

> irb(main):001:0> hexdump = "0408553a09446174655b0b690069006902c0a8553a0d526174696f6e616c5b076c2b0800001a71180269029dff6900660c32323939313631"
irb(main):002:0> require 'date'
=> true
irb(main):003:0> binary = [hexdump].pack('H*')
irb(main):004:0> Marshal.load(binary)
Traceback (most recent call last):
6: from /usr/local/bin/irb-271:23:in `<main>'
5: from /usr/local/bin/irb-271:23:in `load'
4: from /usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
3: from (irb):4
2: from (irb):4:in `load'
1: from (irb):4:in `marshal_load'
ArgumentError (cannot load complex into simple)
irb(main):005:0>

**Comment by zdavatz** [comment]
```
~> ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
~> irb
irb(main):001:0> hexdump = "0408553a09446174655b0b690069006902c0a8553a0d526174696f6e616c5b076c2b0800001a71180269029dff6900660c32323939313631"
irb(main):002:0>  require 'date'
=> true
irb(main):003:0> binary = [hexdump].pack('H*')
irb(main):004:0> Marshal.load(binary)
Traceback (most recent call last):
        6: from /home/zeno/.rbenv/versions/2.7.1/bin/irb:23:in `<main>'
        5: from /home/zeno/.rbenv/versions/2.7.1/bin/irb:23:in `load'
        4: from /home/zeno/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
        3: from (irb):4
        2: from (irb):4:in `load'
        1: from (irb):4:in `marshal_load'
```

**Comment by zdavatz** [comment]
```
~> ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
~> irb
irb(main):001:0> hexdump = "0408553a09446174655b0b690069006902c0a8553a0d526174696f6e616c5b076c2b0800001a71180269029dff6900660c32323939313631"
=> "0408553a09446174655b0b690069006902c0a8553a0d526174696f6e616c5b076c2b0800001a71180269029dff6900660c32323939313631"
irb(main):002:0> require 'date'
=> true
irb(main):003:0> binary = [hexdump].pack('H*')
=> "\x04\bU:\tDate[\vi\x00i\x00i\x02\xC0\xA8U:\rRational[\al+\b\x00\x00\x1Aq\x18\x02i\x02\x9D\xFFi\x00f\f2299161"
irb(main):004:0> Marshal.load(binary)
Traceback (most recent call last):
        4: from /home/zeno/.rbenv/versions/2.5.0/bin/irb:11:in `<main>'
        3: from (irb):4
        2: from (irb):4:in `load'
        1: from (irb):4:in `marshal_load'
ArgumentError (cannot load complex into simple)
```

**Comment by ngiger** [comment]
Bei mir läuft das so:

> niklaus@oddb-ci2 ~/g/oddb.org> irb-250
irb(main):001:0> hexdump = "0408553a09446174655b0b690069006902c0a8553a0d526174696f6e616c5b076c2b0800001a71180269029dff6900660c32323939313631"
=> "0408553a09446174655b0b690069006902c0a8553a0d526174696f6e616c5b076c2b0800001a71180269029dff6900660c32323939313631"
irb(main):002:0> require 'date'
=> true
irb(main):003:0> binary = [hexdump].pack('H*')
=> "\x04\bU:\tDate[\vi\x00i\x00i\x02\xC0\xA8U:\rRational[\al+\b\x00\x00\x1Aq\x18\x02i\x02\x9D\xFFi\x00f\f2299161"
irb(main):004:0> Marshal.load(binary)
=> #<Date: -4712-01-01 ((0j,43200s,(2304000000000/65437)n),+0s,2299161j)>
irb(main):005:0> RUBY_VERSION
=> "2.5.0"
irb(main):006:0>

Bitte benutzer irb-250, eventuell wird irb -> irb-271 umgesetzt.  Mit RUBY_VERSION siehst Du, welche IRB-Version Du verwendest.

**Comment by zdavatz** [comment]
Ok, it depends which `date` gem you have installed. `1.0.0` or `3.0.0`

**Comment by zdavatz** [comment]
see also: https://github.com/ruby/date/issues/20

**Comment by zdavatz** [comment]
Ruby `2.7.1` uses `date.gem-3.0.0` as default. Ruby 2.5.0 use no gem as default.

**Comment by zdavatz** [comment]
Ich habe mal einen `ydate-3.0.1.gem` [Release](https://rubygems.org/gems/ydate) gemacht.

**Comment by zdavatz** [comment]
Date `gem-3.0.1` is out!
