### ISSUE TITLE
OpenSSL::SSL::SSLError: SSL_connect SYSCALL

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#105]
Getting this error after an Openssl upgrade with Ruby-2.5.0:

`drbssl://localhost:9997 - #<OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello>`

![latest-screenshot](https://user-images.githubusercontent.com/4953/84876463-88c66b80-b087-11ea-9e38-18d147d0f220.png)

**Comment by zdavatz** [comment]
`/usr/local/bin/ruby-250 -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'` 
ergibt
`OpenSSL 1.1.1b  26 Feb 2019`
@ngiger kannst Du bitte mal die SSL Version von `DRb` outputten.

**Comment by zdavatz** [comment]
Das sieht gut aus: `curl -Lks 'https://git.io/rg-ssl' | /usr/local/bin/ruby-250`

**Comment by zdavatz** [comment]
@ngiger klappt der Login mit `2.7.1`

**Comment by ngiger** [comment]
On oddb-ci2 I have the following

`niklaus@oddb-ci2 ~/g/yus> /usr/local/bin/ruby-271 -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION
OpenSSL 1.0.2k  26 Jan 2017
niklaus@oddb-ci2 ~/g/yus> /usr/local/bin/ruby-250 -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.2k  26 Jan 2017`

And logging in works fine.

Yus is listening on TCPv4 (address 127.0.0.1:9997) git it via `sudo netstat -tulpen | grep 9997`

**Comment by ngiger** [comment]
On Thinpower Ruby is compiled with OpenSSL 1.1.1b  26 Feb 2019, whereas on oddb-ci2 it is compiled with the OLD version OpenSSL 1.0.2k  26 Jan 2017

**Comment by zdavatz** [comment]
`/usr/local/bin/ruby-250 -ropenssl -e "puts OpenSSL::Config::DEFAULT_CONFIG_FILE || 'dflt missing', ENV['OPENSSL_CONF'] || 'ENV missing'"`

siehe https://github.com/rubygems/rubygems/issues/2388

**Comment by zdavatz** [comment]
https://github.com/ruby/openssl/issues/77#issuecomment-253836305

**Comment by zdavatz** [comment]
lets try this:
https://makandracards.com/makandra/26255-working-around-openssl-ssl-sslerrors
In Ruby, you can teach Net::HTTP to use a specific SSL/TLS version.
```
uri = URI.parse(url)

ssl_options = {
   use_ssl: true,
   ssl_version: 'SSLv3'
}

Net::HTTP.start(uri.host, ssl_options) do |http|
   http.get uri.request_uri
end
```

**Comment by zdavatz** [comment]
https://stackoverflow.com/questions/11059059/is-it-possible-to-enable-tls-v1-2-in-ruby-if-so-how

**Comment by zdavatz** [comment]
[Support client certificates with TLS 1.3 and OpenSSL 1.1.1
](https://github.com/ruby/openssl/issues/237)

**Comment by zdavatz** [comment]
wir könnten es auch mit einem `require 'openssl'` und dem Ruby `openssl-2.2.0.gem` versuchen.

**Comment by zdavatz** [comment]
[OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server hello A](https://stackoverflow.com/questions/25814210/opensslsslsslerror-ssl-connect-syscall-returned-5-errno-0-state-sslv3-read)

**Comment by zdavatz** [comment]
https://github.com/boxen/boxen/issues/221

**Comment by zdavatz** [comment]
Ich schlage vor, dass wir mindestens auf Tls2 umschalten.
[SSL Server Test_ ch.oddb.org (Powered by Qualys SSL Labs).pdf](https://github.com/zdavatz/oddb.org/files/4792337/SSL.Server.Test_.ch.oddb.org.Powered.by.Qualys.SSL.Labs.pdf)

**Comment by ngiger** [comment]
`irb(main):001:0> require 'openssl'
=> true
irb(main):002:0> OpenSSL::SSL::SSLContext::METHODS
(irb):2: warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated
=> [:SSLv23, :SSLv23_client, :SSLv23_server, :SSLv2, :SSLv2_client, :SSLv2_server, :SSLv3, :SSLv3_client, :SSLv3_server, :TLSv1, :TLSv1_client, :TLSv1_server, :TLSv1_1, :TLSv1_1_client, :TLSv1_1_server,:TLSv1_2, :TLSv1_2_client, :TLSv1_2_server]
irb(main):003:0> RUBY_VERSION
=> "2.7.1"`

**Comment by ngiger** [comment]
Die Konfiguration von yus geschieht über bin/yusd (https://github.com/ngiger/yus/blob/master/bin/yusd).
Die verwendeten Schlüssel, etc. werden im /etc/yus/yus.yml definiert, welche aus dem Jahr 2006 stammen

**Comment by ngiger** [comment]
https://ruby-doc.org/stdlib-2.7.1/libdoc/drb/rdoc/DRb/DRbSSLSocket.html

**Comment by zdavatz** [comment]
https://dev.ywesee.com/Niklaus/20151223-yus-ruby-2-x
and
https://dev.ywesee.com/Yasu/20120601-setup-ch-oddb-org

**Comment by ngiger** [comment]
cd /etc/yus/data
mkdir backup
mv yus* backup
openssl req -new -x509 -key ./yus_rsa -out ./yus.crt
# Fails as yus_rsa_not found

**Comment by ngiger** [comment]
openssl req -new -x509 -key ./yus.key -out ./yus.crt

**Comment by zdavatz** [comment]
We created the new keys with above command for `yus`, as we upgraded the Openssl Version.
