### ISSUE TITLE
Import_daily did not run

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#107]
I manually had to start `sudo -u apache /usr/local/bin/ruby-271 jobs/import_daily`

**Comment by zdavatz** [comment]
Updating `/etc/crontab` as following
```
1 19 * * 6       apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/rebuild_indices >/dev/null 2>&1

# run ch.oddb.org updates
1 7 * * *       apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/import_daily >/dev/null 2>&1
1 20 11 * *      apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/import_refdata_nat >/dev/null 2>&1
50 15 * * *     apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/update_drugshortage >/dev/null 2>&1
1 7 * * *       root svc -h /service/migeld
50 7 * * *      root svc -k /service/ch.oddb
50 7 * * *      root svc -k /service/ch.oddb-just-medical
50 7 * * *      root svc -k /service/ch.oddb-generika
31 7 * * *      root svc -k /service/ch.oddb-crawler
32 7 * * *      root svc -k /service/ch.oddb-google_crawler
1 6 * * *       root /etc/init.d/ntp-client restart
#1 2 * * *       apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/export_daily >/dev/null 2>&1
1 6 28 * *      apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/export_fachinfo_yaml
1 6 27 * *      apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/export_patinfo_yaml
1 7 25 8 *      apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/mail_index_therapeuticus_csv

# Debug job
* * * * *       apache /bin/env > /var/log/crontab_env.log 

#http://en.wikipedia.org/wiki/Cron#Format

# run ch.oddb migel-products updates 1st of January and 1st of June (run the BAG update via NovaCantica manually)
1 0 0 6 *       apache cd /var/www/migel && /usr/local/bin/ruby-271 jobs/update_migel_products_with_report >/dev/null 2>&1
1 0 0 1 *       apache cd /var/www/migel && /usr/local/bin/ruby-271 jobs/update_migel_products_with_report >/dev/null 2>&1
```

**Comment by ngiger** [comment]
Danke. Das habe ich vergessen anzupassen. LGAm 18.06.2020 8:17 vorm. schrieb "Zeno R.R. Davatz" <notifications@github.com>:
Updating /etc/crontab as following
1 19 * * 6       apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/rebuild_indices >/dev/null 2>&1

# run ch.oddb.org updates
1 7 * * *       apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/import_daily >/dev/null 2>&1
1 20 11 * *      apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/import_refdata_nat >/dev/null 2>&1
50 15 * * *     apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/update_drugshortage >/dev/null 2>&1
1 7 * * *       root svc -h /service/migeld
50 7 * * *      root svc -k /service/ch.oddb
50 7 * * *      root svc -k /service/ch.oddb-just-medical
50 7 * * *      root svc -k /service/ch.oddb-generika
31 7 * * *      root svc -k /service/ch.oddb-crawler
32 7 * * *      root svc -k /service/ch.oddb-google_crawler
1 6 * * *       root /etc/init.d/ntp-client restart
#1 2 * * *       apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/export_daily >/dev/null 2>&1
1 6 28 * *      apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/export_fachinfo_yaml
1 6 27 * *      apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/export_patinfo_yaml
1 7 25 8 *      apache cd /var/www/oddb.org && /usr/local/bin/ruby-271 jobs/mail_index_therapeuticus_csv

# Debug job
* * * * *       apache /bin/env > /var/log/crontab_env.log 

#http://en.wikipedia.org/wiki/Cron#Format

# run ch.oddb migel-products updates 1st of January and 1st of June (run the BAG update via NovaCantica manually)
1 0 0 6 *       apache cd /var/www/migel && /usr/local/bin/ruby-271 jobs/update_migel_products_with_report >/dev/null 2>&1
1 0 0 1 *       apache cd /var/www/migel && /usr/local/bin/ruby-271 jobs/update_migel_products_with_report >/dev/null 2>&1
