### ISSUE TITLE
Feedback zeigt keine + oder - mehr an

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#108]
z.B.: https://ch.oddb.org/de/gcc/feedbacks/reg/55776/seq/01/pack/009

![feedback](https://user-images.githubusercontent.com/4953/84985370-e8328300-b13c-11ea-9a19-30bc3d7c7a20.png)

**Comment by ngiger** [comment]
Feedback zeigt '-' an. Siehe https://ch.oddb.org/de/gcc/feedbacks/reg/62126/seq/02/pack/005
![image](https://user-images.githubusercontent.com/265800/85291900-68d5e400-b49b-11ea-9d7f-fdcf925fe11e.png)

**Comment by ngiger** [comment]
Obige Item gefunden mit folgendem bin/admin Befehl:

`sorted_feedbacks.find_all{ |x| !x.experience && x.time.year > 2010}.first.item.sequence`

**Comment by zdavatz** [comment]
ok, dann lassen wir das so.
