### ISSUE TITLE
Patinfo Links gehen nicht

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#111]
Alle Patinfo Links gehen nicht, z.B.: https://ch.oddb.org/de/gcc/patinfo/reg/55388/seq/02/pack/014

NoMethodError at /de/gcc/patinfo/reg/57787/seq/01/pack/002
undefined method `photos' for #<ODDB::PatinfoDocument:0x00007fc7c6157120>

**Comment by ngiger** [comment]
Problem nachvollzogenn auf thinpower.
Lokall bei mir führt der Aufruf von https://ch.oddb.org/de/gcc/patinfo/reg/55388 zum gewünschten Resultat
![image](https://user-images.githubusercontent.com/265800/86103003-83701480-babc-11ea-9444-8bc0881da9b2.png)

**Comment by zdavatz** [comment]
heute gehen die Links wieder.

**Comment by zdavatz** [comment]
Es wurden wohl nicht alle Services neu gestartet:

ch.oddb/                      ch.oddb-fiparse/              ch.oddb-just-medical/         ch.oddb-refdata/              
ch.oddb-crawler/              ch.oddb-generika/             ch.oddb-meddata/              ch.oddb-swissindex_nonpharma/ 
ch.oddb-exporter/             ch.oddb-google_crawler/       ch.oddb-readonly/             ch.oddb-swissregd/
