### ISSUE TITLE
Connection refused - connect(2) for "127.0.0.1" port 10005

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#112]
Plugin: ODDB::XlsExportPlugin

Error: DRb::DRbConnError
Message: druby://127.0.0.1:10005 - #<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 10005>
Backtrace:

**Comment by zdavatz** [comment]
Restarting `/service/ch.oddb-exporter/`

**Comment by ngiger** [comment]
With commit https://github.com/zdavatz/oddb.org/commit/2a91d8ab4c83a611c89b922392866d1df7bf444d Update config to use 127.0.0.1 instead of localhost for TCPv4 
various IP adress use a TCP v4 address of 127.0.0.1 instead of localhost which in newer version of ruby/linux reference to IPv6

**Comment by zdavatz** [comment]
works!
