### ISSUE TITLE
FrozenError at /de/just-medical

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#118]
1. Open: https://www.med-drugs.ch/
2. Enter `Mayzent` hit Enter.
3. Following error happens:
![frozen_string](https://user-images.githubusercontent.com/4953/98111279-05c47700-1ea9-11eb-8b8d-b81ff584774d.png)
4. The Direct-Link works: https://just-medical.oddb.org/de/just-medical/fachinfo/reg/67230 but clicking on the Bread-Crumbs "Suchresultat" again generates the error.
5. related: https://dev.ywesee.com/Niklaus/20141124-doctors-view

**Comment by ngiger** [comment]
Fixed with an update to htmlgrid 1.1.9.
Htmlgrid 1.1.9 includes a unit test for this case.
Took 1.5h of work
