### ISSUE TITLE
Remove ydim and syck from oddb.org

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb.org#119]
Exporting yaml objects and invoices is no longer needed.
As we found some problems when migrating to Ruby 3.0.0 when compiling syck, we decided to remove both gems

**Comment by ngiger** [comment]
The following files will be completely removed, which included the possibility to subscribe as poweruser

* ext/export/src/oddb_yaml.rb
* src/plugin/download_invoicer.rb
* src/plugin/info_invoicer.rb
* src/plugin/invoicer.rb
* src/plugin/ydim.rb
* src/util/ipn.rb

**Comment by zdavatz** [comment]
Power-User kann via Kreditkarte bezahlen. Er muss nicht via ydim bezahlen.

**Comment by ngiger** [comment]
Aufwand: 
21.1.21 0.25h
06.1.21 2.25h
