### ISSUE TITLE
Fetching new_atc_codes from who_cc fails

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb.org#122]
Running `test/test_plugin/who.rb` has two failures, which stem from the fact that the URL http://www.whocc.no/atc/lists_of_new_atc_ddds_and_altera/new_atc/?order_by=1&d=DESC is no longer valid.

Looks for me that we might:

1. Change URL form http to https
2. Use ddd/lists_of_temporary_atc_ddds_and_alterations/atc_codes/?order_by=0&d=DESC

**Comment by zdavatz** [comment]
New URLs seem to be:

https://www.whocc.no/atc_ddd_alterations__cumulative/ddd_alterations/
https://www.whocc.no/atc_ddd_alterations__cumulative/atc_alterations/

**Comment by ngiger** [comment]
Bist Du sicher, dass wir beide Seiten besuchen müssen und wird die Anpassungen von 2005 bis 2020 durchsuchen müssen. Meiner Meinung nach wär der Link 
[https://www.whocc.no/ddd/lists_of_temporary_atc_ddds_and_alterations/atc_codes/?order_by=1&d=DESC
](https://www.whocc.no/ddd/lists_of_temporary_atc_ddds_and_alterations/atc_codes/?order_by=1&d=DESC
)
mit der Liste des aktuellesten Jahres gut genug.

**Comment by zdavatz** [comment]
Ja, Entschuldigung, dieser Link genügt: https://www.whocc.no/ddd/lists_of_temporary_atc_ddds_and_alterations/atc_codes/?order_by=1&d=DESC

**Comment by ngiger** [comment]
Aufwand war 1h. jobs/import_whocc lief durch.
Die folgenden Fehler sind soweit ich weiss normal:

`Could not create: :!A16AX14!ddd,O., reason: :!A16AX14!ddd,O. -> OddbPrevalence::atc_class(A16AX14) returned nil
Could not create: :!R03DX09!ddd,P., reason: :!R03DX09!ddd,P. -> OddbPrevalence::atc_class(R03DX09) returned nil`

**Comment by zdavatz** [comment]
Warum kann das nicht gespeichert werden: 

![latest-screenshot](https://user-images.githubusercontent.com/4953/105482810-35656d00-5ca9-11eb-9459-0b37ba01b98f.png)

**Comment by zdavatz** [comment]
Das gleiche gilt für

![latest-screenshot](https://user-images.githubusercontent.com/4953/105483007-7d848f80-5ca9-11eb-824f-9a6d7c77e46c.png)

**Comment by zdavatz** [comment]
diese neuen ATC-Codes müssten eigentlich kreiert und gespeichert werden, damit man Ihnen neue Medikamente zuweisen kann.

**Comment by ngiger** [comment]
Das hast auf ch.oddb.org getestet? Das würde heissen, dass das auch schon unter Ruby 2.7 nicht lief.

**Comment by zdavatz** [comment]
Screenshots sind von ch.oddb.org, von heute.

**Comment by ngiger** [comment]
Okay. Ich lassen den Import nochmals laufen und analysiere das Problem mit pry.

**Comment by ngiger** [comment]
Gemäss [who A16AX14](https://www.whocc.no/atc_ddd_index/?code=A16AX14&showdescription=no) wurde A16AX14 erst im Dezember 20 geändert.
Dito für [[WHO A16AX14](https://www.whocc.no/atc_ddd_index/?code=R03DX09&showdescription=no)
Sehe im pry, dass zuerst eine DDD '0' erstellt werden soll, obwohl die dazugehörende ATC noch nicht existiert.

**Comment by ngiger** [comment]
Aufwand: 22.1.21 1.5h

**Comment by zdavatz** [comment]
See #128
