### ISSUE TITLE
is plugin/vaccines.rb still relevant?

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#124]
The URL mentioned [here](https://github.com/zdavatz/oddb.org/blob/master/src/plugin/vaccines.rb#L32) is [no longer working](https://www.swissmedic.ch/daten/00080/00254/index.html?lang=de):

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/105341718-b8ba8c00-5bdf-11eb-8dc3-03601df62f68.png)

Siehe [zugelassene_packungen_ham.xlsx](https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_human.xlsx.download.xlsx/zugelassene_packungen_ham.xlsx)

**Comment by zdavatz** [comment]
This [Influvac](https://ch.oddb.org/de/gcc/search/zone/drugs/search_query/influvac/search_type/st_oddb?#best_result) search result of oddb.org looks good.

**Comment by zdavatz** [comment]
I think we can remove `plugin/vaccines.rb`

**Comment by ngiger** [comment]
Yes. It should not be a problem. The vaccine flag is set via
[https://github.com/zdavatz/oddb.org/blob/master/src/plugin/swissmedic.rb#L1214](https://github.com/zdavatz/oddb.org/blob/master/src/plugin/swissmedic.rb#L1214)

**Comment by zdavatz** [comment]
ok great!

**Comment by ngiger** [comment]
Aufwand war 1.5h. Spec-Tests laufen
