### ISSUE TITLE
util/tel_search.rb is broken for Ruby 3.0

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb.org#126]
Ruby 3.0 requires you to user URI.open. uri-open does not longer work.
Shown via testcase test/test_util/tel_search.rb

**Comment by zdavatz** [comment]
What does tel search do? I think you can remove this. All doctor adresses are updated via Refdata.

**Comment by ngiger** [comment]
Du hast Recht. Das hat man vergessen auszubauen. Mache ich.

**Comment by ngiger** [comment]
Aufwand 22.1.21 0.5h
