### ISSUE TITLE
Anpassungen spec and unit tests

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb.org#127]
Diverse spec Test laufen nicht mehr, da sich Namen, etc geändert haben, folgende Fehler bis jetzt entdeckt:

* Iscador U gibt es nicht mehr
* Apotheke Moor in Glarus gibt es nicht mehr
* Im Paypal Dialog gibt es kein Element mit ID aswift_0_expand mehr 
* Zwei Test zu RSS-Feeds schlagen fehl, welche von Hand okay sind (werden nicht geflickt)
* Bicalutamid Actavis -> Bicalutamid Sandoz
* Kategory C von Allergo-X gibt es nicht mehr

**Comment by zdavatz** [comment]
Alle Tests die es nicht mehr gibt bitte ausbauen und löschen.

**Comment by ngiger** [comment]
Die meisten Tests wurden angepasst, da die Funktionalität immer noch vorhanden ist.

**Comment by ngiger** [comment]
Aufwand: 22.1.21 3.5h

**Comment by ngiger** [comment]
Bin mit dem Resultat jetzt zufrieden
