### ISSUE TITLE
Create ATC-Code from Swissmedic Import and add description from WHO Import. Both should be possible as Power-User via Admin-Interface.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#128]
Both products `Galafold` and `Nucala` have a 7 digit ATC-Code in `zugelassene_packungen_ham.xlsx`.
![latest-screenshot](https://user-images.githubusercontent.com/4953/105681245-2bce4600-5ef1-11eb-91b8-0738829e9d79.png)
![latest-screenshot](https://user-images.githubusercontent.com/4953/105681284-3f79ac80-5ef1-11eb-839d-a6b928be21f8.png)

Why does oddb.org not show this new ATC-Code already correctly in the Search result? Also see #122 

![latest-screenshot](https://user-images.githubusercontent.com/4953/105681400-60da9880-5ef1-11eb-8986-adf316bdfefe.png)

At least the manual saving the new ATC-Code in the Interface should work.

https://user-images.githubusercontent.com/4953/105482810-35656d00-5ca9-11eb-9459-0b37ba01b98f.png
https://user-images.githubusercontent.com/4953/105483007-7d848f80-5ca9-11eb-824f-9a6d7c77e46c.png

**Comment by ngiger** [comment]
Kannst Du mir die URL angeben, mit der Du den ATC-Code erzeugen lassen willst?

**Comment by zdavatz** [comment]
z.B.:[Nucala](https://ch.oddb.org/de/gcc/drug/reg/67351/seq/01)

**Comment by ngiger** [comment]
Corrected src/plug/swissmedic.rb to catch a situation where a ATC-Code must be created, too.

Fixed src/plug/who.rb to create correctly a new ATC-Code.

Adding a new ATC-code via the admin view was never possible, and it would take me several hours to fix it.

**Comment by zdavatz** [comment]
Can you run the importer to correct it on the server?

**Comment by ngiger** [comment]
As soon as it finished here, which will take a few hours more.

**Comment by zdavatz** [comment]
Ok, then we wait till Swissmedic publishes their new data.

**Comment by ngiger** [comment]
Aufwand (inklusive installation auf thinpower) war 3.25h.

**Comment by zdavatz** [comment]
@ngiger sagt: Habe die gemachten Anpassungen für ATC auf thinpower installiert und service/ch.oddb neu gestartet.
Morgen sollten dann via import_daily die 2 fehlenden ATC-Codes hineinkommen.

**Comment by zdavatz** [comment]
@ngiger ich sehe noch keine neuen ATC-Codes.

**Comment by ngiger** [comment]
Die neuen Codes kommen nur herein, wenn man die betroffenen FIs neu parsed und dazu hat der import-daily im Moment keinen Anlass.

**Comment by zdavatz** [comment]
`sudo -u apache bundle-300 exec ruby-300 jobs/update_textinfo_swissmedicinfo --target=fi --reparse 66108 67350` in screen import_swissmedic laufen, um die beiden Registration aufzudatieren.

**Comment by zdavatz** [comment]
seems to be working but I still get this in the console:
```
2021-02-04 19:02:08 +0100: /var/www/oddb.org/src/plugin/text_info.rb:198:in `ensure_correct_atc_code': ensure_correct_atc_code iksnr 67351 atcFromFI Codice atcFromXml Codice matched and found
2021-02-04 19:02:08 +0100: job is done. now postprocess works ...
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146
Descriptions.description error
/var/www/oddb.org/src/util/language.rb:29:in `description'
/var/www/oddb.org/src/util/language.rb:54:in `method_missing'
/var/www/oddb.org/src/model/fachinfo.rb:79:in `localized_name'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/stub.rb:112:in `method_missing'
/var/www/oddb.org/src/view/rss/fachinfo.rb:85:in `block (2 levels) in to_html'
/var/www/oddb.org/src/view/rss/fachinfo.rb:84:in `each'
/var/www/oddb.org/src/view/rss/fachinfo.rb:84:in `block in to_html'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/rss-0.2.9/lib/rss/maker/base.rb:439:in `make'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/rss-0.2.9/lib/rss/maker.rb:29:in `make'
/var/www/oddb.org/src/view/rss/fachinfo.rb:74:in `to_html'
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146
Descriptions.description error
/var/www/oddb.org/src/util/language.rb:29:in `description'
/var/www/oddb.org/src/util/language.rb:54:in `method_missing'
/var/www/oddb.org/src/util/language.rb:31:in `description'
/var/www/oddb.org/src/util/language.rb:54:in `method_missing'
/var/www/oddb.org/src/model/fachinfo.rb:79:in `localized_name'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/stub.rb:112:in `method_missing'
/var/www/oddb.org/src/view/rss/fachinfo.rb:85:in `block (2 levels) in to_html'
/var/www/oddb.org/src/view/rss/fachinfo.rb:84:in `each'
/var/www/oddb.org/src/view/rss/fachinfo.rb:84:in `block in to_html'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/rss-0.2.9/lib/rss/maker/base.rb:439:in `make'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146
```

**Comment by zdavatz** [comment]
Für `Galafold` hat es geklappt, nicht aber für `Nucala`, siehe

![latest-screenshot](https://user-images.githubusercontent.com/4953/106936061-67041c80-671c-11eb-9216-d9a422f5a307.png)

hier ist jetzt etwas doppelt.

**Comment by ngiger** [comment]
Via bin/admin erhalte ich:
```ch.oddb> registration('67350').atc_class.class
-> ODDB::AtcClass
ch.oddb> registration('67350').atc_class.code
-> Codice
ch.oddb> registration('67350').atc_class.name
->
ch.oddb> registration('66108').atc_class.class
-> ODDB::AtcClass
ch.oddb> registration('66108').atc_class.code
-> A16AX14
ch.oddb> registration('66108').atc_class.name
->
ch.oddb> atc_class('A16AX14').class
-> NilClass
ch.oddb> atc_class('R03DX09').class
-> NilClass
```
Irgendwas ist hier schief. Lasse mal zuerst noch den who importer laufen.

**Comment by zdavatz** [comment]
I am now running this `sudo -u apache bundle-300 exec ruby-300 jobs/update_textinfo_swissmedicinfo --target=fi --reparse 66108 67350` again in `screen -x 14948`

**Comment by zdavatz** [comment]
these Errors are still coming: 
![latest-screenshot](https://user-images.githubusercontent.com/4953/107002744-fb599800-678b-11eb-95c5-6e597c87f2ed.png)

**Comment by zdavatz** [comment]
Login in as root User and setting the ATC-Code via Web-Interface results in

![latest-screenshot](https://user-images.githubusercontent.com/4953/107003134-95214500-678c-11eb-8ee9-ca4ea4cbd7d9.png)

but the Information is saved.

**Comment by zdavatz** [comment]
Ok, I fixed manually via the interface as [Admin User](https://ch.oddb.org/de/gcc/drug/reg/67350/seq/01).
