### ISSUE TITLE
Could not create: :!!sequence,02!package,002!sl_entry!limitation_text., reason:

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#133]
What does this mean? I get this Error when I run `sudo -u apache bundle-300 exec ruby-300 jobs/import_bsv`

```
Could not create: :!!sequence,02!package,002!sl_entry!limitation_text., reason: :!!sequence,02!package,002!sl_entry!limitation_text. -> undefined Method OddbPrevalence::66709()
Could not create: :!!sequence,02!package,002!sl_entry!limitation_text., reason: :!!sequence,02!package,002!sl_entry!limitation_text. -> undefined Method OddbPrevalence::67102()
Could not create: :!!sequence,01!package,006!sl_entry!limitation_text., reason: :!!sequence,01!package,006!sl_entry!limitation_text. -> undefined Method OddbPrevalence::65673()
Could not create: :!!sequence,02!package,007!sl_entry!limitation_text., reason: :!!sequence,02!package,007!sl_entry!limitation_text. -> undefined Method OddbPrevalence::65673()
Could not create: :!!sequence,03!package,008!sl_entry!limitation_text., reason: :!!sequence,03!package,008!sl_entry!limitation_text. -> undefined Method OddbPrevalence::65673()
Could not create: :!!sequence,01!package,001!sl_entry!limitation_text., reason: :!!sequence,01!package,001!sl_entry!limitation_text. -> undefined Method OddbPrevalence::67537()
Could not create: :!!sequence,01!package,001!sl_entry!limitation_text., reason: :!!sequence,01!package,001!sl_entry!limitation_text. -> undefined Method OddbPrevalence::67534()
```

**Comment by zdavatz** [comment]
seems that lots of Limitation Text can not be created.

**Comment by ngiger** [comment]
When does this error come? Import-Daily? Accessing a given page?

**Comment by zdavatz** [comment]
`sudo -u apache bundle-300 exec ruby-300 jobs/import_bsv` then when the Limitation texts are created.

**Comment by ngiger** [comment]
This error was introduce with commit 
`64a22e00be2b41f7519950319496eb5dfa370114 Rescue to avoid error in outdated pack (Limitation)`

The call to `app.update txt_ptr.creator, lim_data, :bag` must be only made, when the txt_ptr is not empty (e.g. there is a limitation

Fix is easy. Waiting for import_bsv to finish

**Comment by ngiger** [comment]
But know I have more errors like `:!registration,57616!sequence,01!001!part. -> ODDB::Sequence::package(001) returned nil`.
Suspecting a similar problem there, trying a fix. Restarting import

**Comment by ngiger** [comment]
Or do I have to revert the commit https://github.com/zdavatz/oddb.org/commit/2f3b9f13580330a3913d2b344d448ffed7026e27
by Masa on Sep 10,2010 `Temporary treatment for missing limitation text link`.
He discussed it in https://dev.ywesee.com/Masa/20100928-resolve-missing-link-limitation-bug
But no idea, what to is really to do yet.

**Comment by ngiger** [comment]
I have spent over 3 hours to find a solution, but I still have no clue why we see this message. As it traces back 10 years, I suggest that we just continue to ignore it.

**Comment by zdavatz** [comment]
The Limitations Texts did not vanish 10 years ago. We have to bring back the limitations texts.

**Comment by ngiger** [comment]
Bei mir wird https://ch.oddb.org/de/gcc/limitation_text/reg/61261/seq/01/pack/002 richtig angezeigt.

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/111179732-a55aea00-85ac-11eb-951f-e0e8d386fa2a.png)

**Comment by zdavatz** [comment]
Hier noch ein Screen: ![latest-screenshot](https://user-images.githubusercontent.com/4953/111180130-0387cd00-85ad-11eb-87e7-415078f1710b.png)

**Comment by ngiger** [comment]
There are limitations to be found on ch.oddb.org. z.B. Abraxane.

Ex: https://ch.oddb.org/de/gcc/limitation_text/reg/63182/seq/01/pack/001
Which display an  'L' under https://ch.oddb.org/de/gcc/search/zone/drugs/search_query/Abraxane/search_type/st_sequence?
And it can be found in Preparations.xml viaa
```
grep -w 63182 Preparations.xml
<SwissmedicNo5>63182</SwissmedicNo5>
```

The registry 612621 does not have a limitationtext in Preparations.xml (`grep -w 612621 Preparations.xml`) returns nothing.

**Comment by zdavatz** [comment]
> Hier noch ein Screen: ![latest-screenshot](https://user-images.githubusercontent.com/4953/111180130-0387cd00-85ad-11eb-87e7-415078f1710b.png)

im Vergleich dazu:
![Bildschirmfoto 2021-03-15 um 19 25 43](https://user-images.githubusercontent.com/4953/111202549-45703d80-85c4-11eb-8749-4f7440f56d5e.png)

**Comment by ngiger** [comment]
66709 Entecavir Mepha is a perfect example. In Preparations.xml there is no limitation for sequence 01 (GTIN 7680667090014) , but 02 (GTIN 7680667090021) has limitiation "Nur bei Patienten, die eine Resistenz gegen die Lamivudin-Behandlung entwickelt haben. (Second line)."

Following entry in my log are
```
limitation delete sl_data for :!registration,66709!sequence,01!package,001.
limitation store sl_data for :!registration,66709!sequence,02!package,002. 66709 Entecavir Mepha lim: Entecavir Mepha
import_bsv-11.log-
import_bsv-11.log-Nur bei Patienten, die eine Resistenz gegen die Lamivu
SKIP error limitation delete txt_ptr for :!66709!sequence,02!package,002!sl_entry!limitation_text.
limitation update txt_ptr for :!66709!sequence,02!package,002!sl_entry!limitation_text.
Could not create: :!!sequence,02!package,002!sl_entry!limitation_text., reason: :!!sequence,02!package,002!sl_entry!limitation_text. -> undefined Method OddbPrevalence::66709()
import_bsv-11.log-limitation delete sl_data for :!registration,67102!sequence,01!package,001.
import_bsv-11.log-limitation store sl_data for :!registration,67102!sequence,02!package,002. 67102 Entecavir Mylan lim: Entecavir Mylan
```

And http://192.168.0.75:8012/de/gcc/search/zone/drugs/search_query/Entecavir/search_type/st_sequence?#best_result shows no 'L' for Mepha (Same picture as above).

**Comment by ngiger** [comment]
Narrowing down the problem. The variable `txt_ptr = sl_ptr + :limitation_text` changes its between its definition from (`:!registration,57831!sequence,02!package,004!sl_entry!limitation_text`) and the call to `@app.update txt_ptr.creator, lim_data, :bag` to ` :!57831!sequence,02!package,004!sl_entry!limitation_text`.

Workaround is to recreate it again there. Adding a txt_ptr.freeze to see, whether I can find out where its value is being changed.

**Comment by ngiger** [comment]
Cleaned up the changes. Reimport the DB from thinpower and rerunning the whole import_bsv to be sure.

**Comment by ngiger** [comment]
Habe seit Freitag 5.5h auf dieses Problem aufgewendet? Ist das okay, wenn ich diese Dir verrechne?

**Comment by zdavatz** [comment]
seit wann existiert das Problem?

**Comment by ngiger** [comment]
Das weiss ich nicht genau. Könnte sein, dass dies ein Bug in Ruby 3.0 ist, da mir nicht klar, wo diese Variable txt_ptr geändert werden könnte.
Ansonsten im im bsv_xml plugin seit Juni 2020 nix mehr geändert worden. Die Anpassungen in 2020 betrafen nur Dateinamen. 
Im 2017 habe ich eine Änderung gemacht, die mit dem Issue 133 zusammenhängen könnte.
Es gibt in den Spec-Tests aber nix, das explizit die Limitationen testet, deshalb ist die Chance, dass mir was auffällt auch sehr klein gewesen, da einige Limitationen ja immer noch angezeigt wurden.

**Comment by zdavatz** [comment]
Der Error welcher beim Job `sudo -u apache bundle-300 exec ruby-300 jobs/import_bsv` gezeigt wurde, war offenbar immer vorhanden.
