### ISSUE TITLE
bei Swisssrugupdate fehlen Produkte

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#146]
Mit fällt auf, dass du uns weder im Mai noch jetzt im Juni irgend eine Neueinführung lieferst. Kann dies wirklich sein?
Ohnehin sind die Listen sehr kurz.

**Comment by ngiger** [comment]
Ich liefere nie eine Neueinführung. Höchstens der Code, den ich geschrieben habe.
Habe gesehen, dass z.B aus  der Datei refdata_Pharma.xml aus den Zeilen
<pre>
juni/refdata_Pharma.xml-      <ITEM DT="2021-05-25T00:00:00">
juni/refdata_Pharma.xml-        <ATYPE>PHARMA</ATYPE>
juni/refdata_Pharma.xml:        <GTIN>7680681620020</GTIN>
juni/refdata_Pharma.xml-        <SWMC_AUTHNR>68162002</SWMC_AUTHNR>
juni/refdata_Pharma.xml-        <NAME_DE>ROSUVASTATIN Xiromed Filmtabl 5 mg 100 Stk</NAME_DE>
juni/refdata_Pharma.xml-        <NAME_FR>ROSUVASTATIN Xiromed cpr pell 5 mg 100 pce</NAME_FR>
juni/refdata_Pharma.xml-        <AUTH_HOLDER_NAME>Xiromed SA</AUTH_HOLDER_NAME>
juni/refdata_Pharma.xml-        <AUTH_HOLDER_GLN>7601001411364</AUTH_HOLDER_GLN>
juni/refdata_Pharma.xml-      </ITEM>
</pre>
Nichts unter ch.oddb.org zu finden ist. Werde dem morgen nachgehen.

**Comment by zdavatz** [comment]
`Code 1` sind `Neuregistrierungen`, diese kommen rein via `Swissmedic-Diff`, siehe: https://dev.ywesee.com/Oddb/MedDrugsUpdate

**Comment by ngiger** [comment]
Nach langem Suchen, habe ich gefunden, dass die `@app.log_group(:swiss_medic)` https://github.com/zdavatz/oddb.org/blob/e09059f72e4cd3bc3ce0ac8684c5e1d3f328add1/src/plugin/ouwerkerk.rb#L91 leer ist, während dem 
<pre>
> puts @app.log_group(:bsv_sl).latest.report
Created SL-Entries                                           67
Updated SL-Entries                                         9319
Deleted SL-Entries                                           18
Created Limitation-Texts                                     15
Updated Limitation-Texts                                   2516
Deleted Limitation-Texts                                      0
Duplicate Registrations in SL 01.04.2021                      0
Package-Data was completed from SL                           11
SMeX/SL-Differences (Registrations) 01.04.2021                3
Missing Swissmedic-Codes in SL 01.04.2021                     0
Missing Swissmedic-Codes in SL (out of trade) 01.04.2021      0
Unknown Packages in SL 01.04.2021                           449
Unknown Packages in SL (out of trade) 01.04.2021              0
Packungen in der ODDB Total: 19824
- ausser Handel: 19821
- inaktive Registration: 0
- noch nicht auf MedWin: 3
</pre>
Alle benötigten Informationen erhält.

Schlussfolgerung. Beim swissmedic plugin wird die loggroup nicht richtig gesetzt.

**Comment by ngiger** [comment]
Habe auf thinpower `sudo -u apache bundle-300 exec ruby-300 jobs/export_swissdrug-update` laufen lassen.
Jetzt enthält /var/www/oddb.org/data/xls/med-drugs-20210604.xls wieder 90 Einträge mit der Kategorie 1.

Ich vermute, dass die Fehler daher stammen, dass der swissmedic-import mehrmals lief und keine Neueinträge mehr lieferte.
Da gestern aber ein neues Packungen.xlsx erstellt wurde, hatte er heute die benötigten Einträge.

Falls das nächsten Monat wieder nicht klappt, wäre noch die Frage, ob die logs erst ganz am Ende (also nach den followers) in die DB geschrieben werden.

Aufwand bis jetzt: 2.5h

**Comment by zdavatz** [comment]
Wieviele Zeilen hat das neue File?

**Comment by ngiger** [comment]
1086 Zeilen

**Comment by zdavatz** [comment]
Perfekt, Danke!

**Comment by zdavatz** [comment]
Gleiches Problem wieder passiert im September 2021. Swissmedic hat nochmals ein neues File publiziert, das hat alle Logs wieder auf 0 gesetzt. Eigentlich müssten immer zwei Files gedifft werden.
