### ISSUE TITLE
Search for `Prostaplant-F` throws error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#159]
Error comes when logged in:

![E90872A0-BA7D-419F-80A2-99018A69C676](https://user-images.githubusercontent.com/4953/167412198-5e3cf15e-9413-4e32-a196-5fa2131c2935.jpeg)

**Comment by ngiger** [comment]
Habe kein WLAN für mein Laptop. Ideen: 
Postgres Prozesse für yus killen.
Yus DB neu aus Dump laden
Hoffe auf besseres WLAN morgen im Hotel

Am May 9, 2022 12:43:43 PM UTC schrieb "Zeno R.R. Davatz" ***@***.***>:
>Error comes when logged in:
>
>![E90872A0-BA7D-419F-80A2-99018A69C676](https://user-images.githubusercontent.com/4953/167412198-5e3cf15e-9413-4e32-a196-5fa2131c2935.jpeg)
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/zdavatz/oddb.org/issues/159
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit Librem Mail gesendet.

**Comment by zdavatz** [comment]
Works again after restarting `yus`.
