### ISSUE TITLE
`oekk.oddb.org` throws an encoding error, US-ASCII and UTF-8

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#190]
1. The domain https://oekk.oddb.org throws the following error:
2. ![Bildschirm­foto 2023-01-02 um 21 40 23](https://user-images.githubusercontent.com/4953/210276520-c42bb809-e031-4893-8706-114b742b0fba.png)
```
Encoding::CompatibilityError: incompatible character encodings: US-ASCII and UTF-8
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/htmlgrid-1.2.2/lib/htmlgrid/template.rb:134:in `block in template_html'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/3.1.0/cgi/html.rb:55:in `nO_element'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/3.1.0/cgi/html.rb:62:in `nO_element_def'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/3.1.0/cgi/html.rb:423:in `html'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/htmlgrid-1.2.2/lib/htmlgrid/template.rb:133:in `template_html'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/htmlgrid-1.2.2/lib/htmlgrid/template.rb:149:in `to_html'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/state.rb:175:in `to_html'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/session.rb:547:in `to_html'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/session.rb:279:in `block in process_rack'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/session.rb:209:in `synchronize'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/session.rb:209:in `process_rack'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/app.rb:126:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/lint.rb:50:in `_call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/lint.rb:38:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/show_exceptions.rb:23:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/content_length.rb:17:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/static.rb:161:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/lint.rb:50:in `_call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/lint.rb:38:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/show_exceptions.rb:23:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/content_length.rb:17:in `call'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.4/lib/rack/handler/webrick.rb:95:in `service'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
	/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
```

**Comment by zdavatz** [comment]
[oddb-ssl.conf.txt](https://github.com/zdavatz/oddb.org/files/10336058/oddb-ssl.conf.txt)

**Comment by zdavatz** [comment]
Der Flavor geht auch nicht: https://ch.oddb.org/de/oekk

**Comment by ngiger** [comment]
Bei mir geht der Aufruf von http://192.168.0.75:8012/de/oekk
![image](https://user-images.githubusercontent.com/265800/210347799-2032546c-0d78-4675-8b05-02705b1b5cf5.png)

**Comment by zdavatz** [comment]
welche Ruby Version? Bist Du auch auf 3.1.1 mit YJIT aktiviert?

**Comment by zdavatz** [comment]
Gems included by the bundle:
  * activesupport (7.0.1)
  * addressable (2.8.0)
  * akami (1.3.1)
  * ast (2.4.2)
  * bigdecimal (3.1.1)
  * builder (3.2.4)
  * childprocess (4.1.0)
  * chrono_logger (1.1.2)
  * clogger (2.3.1)
  * cmath (1.0.0)
  * concurrent-ruby (1.1.9)
  * connection_pool (2.2.5)
  * crack (0.4.5)
  * data_magic (1.2)
  * dbi (0.4.6 ce41c14)
  * deprecated (2.0.1)
  * diff-lcs (1.5.0)
  * digest (3.1.0)
  * docile (1.4.0)
  * domain_name (0.5.20190701)
  * faker (2.19.0)
  * flexmock (2.3.6)
  * flickraw (0.9.10)
  * gruff (0.8.0)
  * gyoku (1.3.1)
  * hashdiff (1.0.1)
  * highline (2.0.3)
  * hpricot (0.8.6)
  * htmlentities (4.3.4)
  * htmlgrid (1.2.2)
  * http-cookie (1.0.5)
  * httpi (2.5.0)
  * i18n (1.8.11)
  * io-wait (0.2.1)
  * json (2.6.1)
  * mail (2.7.1)
  * mechanize (2.8.5)
  * mime-types (3.4.1)
  * mime-types-data (3.2022.0105)
  * mimemagic (0.4.3)
  * mini_mime (1.1.2)
  * mini_portile2 (2.8.0)
  * minitar (0.9)
  * minitest (5.15.0)
  * minitest-should_syntax (1.0.2)
  * minitest-spec-expect (2.0.0)
  * money (6.16.0)
  * multi_json (1.15.0)
  * needle (1.3.0)
  * net-http-digest_auth (1.4.1)
  * net-http-persistent (4.0.1)
  * net-imap (0.2.3)
  * net-pop (0.1.1)
  * net-protocol (0.1.2)
  * net-smtp (0.3.1)
  * nokogiri (1.13.10)
  * nori (2.6.0)
  * odba (1.1.8)
  * oddb2tdat (1.1.2)
  * optimist (3.0.1)
  * ox (2.14.6)
  * page-object (2.3.1)
  * page_navigation (0.10)
  * parallel (1.21.0)
  * parser (3.1.0.0)
  * parslet (2.0.0)
  * paypal (2.0.0)
  * pg (1.2.3)
  * public_suffix (4.0.7)
  * racc (1.6.0)
  * rack (2.2.4)
  * rack-test (1.1.0)
  * rackup (0.1.0)
  * rainbow (3.1.1)
  * rake (13.0.6)
  * rbs (2.0.0)
  * rclconf (1.0.0)
  * regexp_parser (2.2.0)
  * rexml (3.2.5)
  * rmagick (4.2.4)
  * rspec (3.10.0)
  * rspec-core (3.10.1)
  * rspec-expectations (3.10.1)
  * rspec-mocks (3.10.2)
  * rspec-support (3.10.3)
  * rss (0.2.9)
  * rubocop (1.24.1)
  * rubocop-ast (1.15.1)
  * rubocop-performance (1.13.1)
  * ruby-ole (1.2.12.2)
  * ruby-progressbar (1.11.0)
  * ruby-units (2.3.2)
  * rubyXL (3.4.18)
  * rubyntlm (0.6.3)
  * rubyzip (2.3.2)
  * savon (2.12.1)
  * sax-machine (1.3.2)
  * sbsm (1.6.0)
  * selenium-webdriver (4.1.0)
  * simplecov (0.21.2)
  * simplecov-html (0.12.3)
  * simplecov_json_formatter (0.1.3)
  * socksify (1.7.1)
  * spreadsheet (1.3.0)
  * standard (1.6.0)
  * strscan (3.0.1)
  * swissmedic-diff (0.2.7)
  * timeout (0.2.0)
  * travis-lint (2.0.0)
  * typeprof (0.21.2)
  * tzinfo (2.0.4)
  * unf (0.1.4)
  * unf_ext (0.0.8.2)
  * unicode-display_width (2.1.0)
  * vcr (6.0.0)
  * wasabi (3.6.1)
  * watir (7.1.0)
  * watir-scroll (0.4.0)
  * watir-webdriver (0.9.9)
  * webdrivers (5.0.0)
  * webmock (3.14.0)
  * webrick (1.7.0)
  * webrobots (0.1.2)
  * ydbd-pg (0.5.9)
  * ydbi (0.5.9)
  * ydiffy (0.0.2)
  * ydocx (1.2.6)
  * yml_reader (0.7)
  * yus (1.0.6)
Use `bundle info` to print more detailed information about a gem

**Comment by zdavatz** [comment]
1. Grep or non UTF-8 characters: 
2. `grep -P "[\x80-\xFF]" file`
3. `grep -axv '.*' file.txt`
