### ISSUE TITLE
Fachinfo Diff incompatible character encoding

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#194]
https://ch.oddb.org/de/gcc/show/fachinfo/59322/diff/04.01.2023
https://ch.oddb.org/de/gcc/show/fachinfo/65512/diff/09.01.2023
https://ch.oddb.org/de/gcc/show/fachinfo/65770/diff/10.01.2023

**Comment by ngiger** [comment]
On oddb-ci2 I had no problems displaying the diffs. Used the following URLs:

http://192.168.0.75:8012/de/gcc/show/fachinfo/59322/diff/05.01.2023

http://192.168.0.75:8012/de/gcc/show/fachinfo/65512/diff/10.01.2023
http://192.168.0.75:8012/de/gcc/show/fachinfo/65512/diff/09.01.2023
http://192.168.0.75:8012/de/gcc/show/fachinfo/65512/diff/05.01.2023

http://192.168.0.75:8012/de/gcc/show/fachinfo/65770/diff/10.01.2023

**Comment by zdavatz** [comment]
What is your `locale`?
```
zdavatz@ch:~$ locale
LANG=de_CH.UTF-8
LANGUAGE=
LC_CTYPE="de_CH.UTF-8"
LC_NUMERIC="de_CH.UTF-8"
LC_TIME="de_CH.UTF-8"
LC_COLLATE=C
LC_MONETARY="de_CH.UTF-8"
LC_MESSAGES="de_CH.UTF-8"
LC_PAPER="de_CH.UTF-8"
LC_NAME="de_CH.UTF-8"
LC_ADDRESS="de_CH.UTF-8"
LC_TELEPHONE="de_CH.UTF-8"
LC_MEASUREMENT="de_CH.UTF-8"
LC_IDENTIFICATION="de_CH.UTF-8"
LC_ALL=
```

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/211529719-70a89780-6010-4b38-b373-aa47ec8115ac.png)

**Comment by ngiger** [comment]
Mine is
<pre>
locale
LANG=de_CH.UTF-8
LC_CTYPE="de_CH.UTF-8"
LC_NUMERIC="de_CH.UTF-8"
LC_TIME="de_CH.UTF-8"
LC_COLLATE="de_CH.UTF-8"
LC_MONETARY="de_CH.UTF-8"
LC_MESSAGES="de_CH.UTF-8"
LC_PAPER="de_CH.UTF-8"
LC_NAME="de_CH.UTF-8"
LC_ADDRESS="de_CH.UTF-8"
LC_TELEPHONE="de_CH.UTF-8"
LC_MEASUREMENT="de_CH.UTF-8"
LC_IDENTIFICATION="de_CH.UTF-8"
LC_ALL=de_CH.UTF-8
</pre>

And posgres is
<pre>
ostgres=# \l
                                    List of databases
      Name      |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
----------------+----------+----------+-------------+-------------+-----------------------
 ch_oddb        | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 migel          | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres       | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 sandoz_xmlconv | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
                |          |          |             |             | postgres=CTc/postgres
 template1      | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | postgres=CT/postgres +
                |          |          |             |             | =c/postgres
 test           | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 ydim           | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 yus            | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
(9 rows)
</pre>

**Comment by ngiger** [comment]
I think the following commit (which is present on oddb-ci2) fixed the problem: https://github.com/zdavatz/oddb.org/commit/99b993f62510e5627969c0446275c30605531532

**Comment by zdavatz** [comment]
Ok, lets check back on Ruby 3.2.0

**Comment by zdavatz** [comment]
https://github.com/zdavatz/ydiffy/blob/master/lib/diffy/html_formatter.rb

**Comment by zdavatz** [comment]
zdavatz@ch:~$ locale
LANG=de_CH.UTF-8
LANGUAGE=de_CH.UTF-8
LC_CTYPE="de_CH.UTF-8"
LC_NUMERIC="de_CH.UTF-8"
LC_TIME="de_CH.UTF-8"
LC_COLLATE="de_CH.UTF-8"
LC_MONETARY="de_CH.UTF-8"
LC_MESSAGES="de_CH.UTF-8"
LC_PAPER="de_CH.UTF-8"
LC_NAME="de_CH.UTF-8"
LC_ADDRESS="de_CH.UTF-8"
LC_TELEPHONE="de_CH.UTF-8"
LC_MEASUREMENT="de_CH.UTF-8"
LC_IDENTIFICATION="de_CH.UTF-8"
LC_ALL=de_CH.UTF-8

**Comment by ngiger** [comment]
Added a testcase as per [(#194) Added a testcase for 59322](https://github.com/ngiger/oddb.org/commit/0d5ccca5b0b24e10e2759fef703dc10f9b39e524)

But it does not throw an error.  Unsure whether this might be a problem with the apache setup and its handling of UTF-8.

**Comment by zdavatz** [comment]
ydiffy-0.0.5 fixes this.
