### ISSUE TITLE
`import_daily` error with Ruby 3.2.0

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#198]
1. Running `job/import_daily` with ruby 3.2.0 results in
```
Plugin: ODDB::TextInfoPlugin
 Error: NoMethodError
 Message: undefined method `push' for #<ODDB::PatinfoDocument:0x0000
7fd55ab10c88 @odba_persistent=true, @odba_prefetch=nil, @galenic_form=nil, @effects=#<ODBA::Stub:25777720#39403594 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @amendments=#<ODBA::Stub:25777740#39403595 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @contra_indications=#<ODBA::Stub:25777760#39403596 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @oid=38363678, @precautions=#<ODBA::Stub:25777780#39403597 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @pregnancy=#<ODBA::Stub:25777800#39403598 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @revision=2018-07-04 07:50:18.056638039 +0200, @unwanted_effects=#<ODBA::Stub:25777820#39403600 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @general_advice=#<ODBA::Stub:25777840#39403601 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @composition=#<ODBA::Stub:25777860#39403602 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @packages=#<ODBA::Stub:25777880#39403603 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @distribution=nil, @usage=#<ODBA::Stub:25777900#39403599 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @fabrication=nil, @iksnrs=#<ODBA::Stub:25777920#39403591 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @date=#<ODBA::Stub:25777940#39403604 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @name=#<ODBA::Stub:25777960#39403592 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @odba_observers=[], @company=#<ODBA::Stub:25777980#39403593 @odba_class=ODDB::Text::Chapter @odba_container=25773440#38363678>, @odba_id=38363678>
 Backtrace:
 /var/www/oddb.org/src/model/fachinfo.rb:192:in `add_change_log_item'
 /var/www/oddb.org/src/plugin/text_info.rb:167:in `store_fachinfo'
 /var/www/oddb.org/src/plugin/text_info.rb:271:in `update_fachinfo_lang'
 /var/www/oddb.org/src/plugin/text_info.rb:1296:in `parse_textinfo'
 /var/www/oddb.org/src/plugin/text_info.rb:1499:in `block in import_swissmedicinfo'
 /var/www/oddb.org/src/plugin/text_info.rb:1498:in `each'
 /var/www/oddb.org/src/plugin/text_info.rb:1498:in `import_swissmedicinfo'
 /var/www/oddb.org/src/util/updater.rb:541:in `block in update_notify_simple'
 /var/www/oddb.org/src/util/updater.rb:497:in `wrap_update'
 /var/www/oddb.org/src/util/updater.rb:535:in `update_notify_simple'
 /var/www/oddb.org/src/util/updater.rb:329:in `update_textinfo_swissmedicinfo'
 /var/www/oddb.org/src/util/updater.rb:209:in `run'
 jobs/import_daily:13:in `block in <module:Util>'
 /var/www/oddb.org/src/util/job.rb:41:in `run'
 jobs/import_daily:12:in `<module:Util>'
 jobs/import_daily:11:in `<module:ODDB>'
 jobs/import_daily:10:in `<main>'
```

**Comment by ngiger** [comment]
Also I have seen the following error in log/oddb/debug/2023/01.log
<pre>2023-01-05 16:42:07 +0100: /var/www/oddb.org/src/util/oddbapp.rb:1493:in `rescue in initialize': Error initializing can't alloc machine stack to fiber (1 x 659456 bytes): Cannot allocate memory with @@primary_server </pre>

**Comment by zdavatz** [comment]
looks like a global variable error ;)

**Comment by ngiger** [comment]
Running the import_daily another with just a begin/rescue clause to get into the pry. I get an memory error:
<pre>
2023-01-09 16:12:26 +0100: /var/www/oddb.org/src/plugin/text_info.rb:353:in `store_package_patinfo': called odba_store 67324/01/001: fr Amavita Diclofénac 25, Capsules change_diff
Util.log_and_deliver_mail
Plugin: ODDB::TextInfoPlugin

Error: RegexpError
Message: failed to allocate memory: /<content><!\[CDATA\[(.*)\]\]><\/content/mi
Backtrace:
/var/www/[oddb.org/src/plugin/text_info.rb:1209:in](http://oddb.org/src/plugin/text_info.rb:1209:in) `match'
/var/www/[oddb.org/src/plugin/text_info.rb:1209:in](http://oddb.org/src/plugin/text_info.rb:1209:in) `extract_html'
/var/www/[oddb.org/src/plugin/text_info.rb:1258:in](http://oddb.org/src/plugin/text_info.rb:1258:in) `parse_textinfo'
/var/www/[oddb.org/src/plugin/text_info.rb:1506:in](http://oddb.org/src/plugin/text_info.rb:1506:in) `block in import_swissmedicinfo'
/var/www/[oddb.org/src/plugin/text_info.rb:1505:in](http://oddb.org/src/plugin/text_info.rb:1505:in) `each'
/var/www/[oddb.org/src/plugin/text_info.rb:1505:in](http://oddb.org/src/plugin/text_info.rb:1505:in) `import_swissmedicinfo'
/var/www/[oddb.org/src/util/updater.rb:541:in](http://oddb.org/src/util/updater.rb:541:in) `block in update_notify_simple'
/var/www/[oddb.org/src/util/updater.rb:497:in](http://oddb.org/src/util/updater.rb:497:in) `wrap_update'
/var/www/[oddb.org/src/util/updater.rb:535:in](http://oddb.org/src/util/updater.rb:535:in) `update_notify_simple'
/var/www/[oddb.org/src/util/updater.rb:329:in](http://oddb.org/src/util/updater.rb:329:in) `update_textinfo_swissmedicinfo'
/var/www/[oddb.org/src/util/updater.rb:210:in](http://oddb.org/src/util/updater.rb:210:in) `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/[oddb.org/src/util/job.rb:41:in](http://oddb.org/src/util/job.rb:41:in) `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
</pre>
Logging some memory useage and restarting the import

**Comment by zdavatz** [comment]
Memory usage should be much better with YJIT enabled.

**Comment by ngiger** [comment]
This is the case looking at ./doc/resources/downloads/status_* I see memory useage between 920 and 3300 MB.
But maybe the Fiber need some special treatment. No idea, will look into it tomorrow

**Comment by ngiger** [comment]
Pushed another commit to avoid touching change_log. 
With this patch import_daily passed without problem on oddb-ci2.
