### ISSUE TITLE
AIPS form button throws an error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#208]
1. `jobs/import_daily` throws the following error:
```
#<Thread:0x00007fd097a898b8 /var/www/oddb.org/src/plugin/text_info.rb:1481 run> terminated with exception (report_on_exception is true):
/var/www/oddb.org/src/plugin/text_info.rb:810:in `textinfo_swissmedicinfo_index': undefined method `button_with' for nil:NilClass (NoMethodError)

      button = form.button_with(:name => 'ctl00$MainContent$btnOK')
                   ^^^^^^^^^^^^
        from /var/www/oddb.org/src/plugin/text_info.rb:1482:in `block in import_swissmedicinfo'
```
2. Has the name of the button changed?
3. ![latest-screenshot](https://user-images.githubusercontent.com/4953/214266845-e4d98d51-9fa1-40bd-a104-e2323d131dbf.png)

**Comment by ngiger** [comment]
Adding a pry debug. Looks like the links to the new/changes items has changed. E.g.
https://www.swissmedicinfo.ch/UpdatedTexts.aspx?Lang=DE
Where we expected before http://www.swissmedicinfo.ch/New?Lang=DE
