### ISSUE TITLE
Ganirelix NoMethod Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#249]
Die Suche nach Ganirelix wirft einen NoMethod Error.

these two searches do not work, also for `Orgalutran`
![IMG_2013](https://github.com/zdavatz/oddb.org/assets/4953/3e4384a5-ebe4-4a6a-b852-8f5c33b07208)

**Comment by zdavatz** [comment]
This works: https://ch.oddb.org/de/mobile/search/zone/drugs/search_query/68549/search_type/st_registration?

**Comment by ngiger** [comment]
```
(ruby) @sequences[3].iksnr
"68792"
(ruby) @sequences[3].packages.class
ODDB::PatinfoDocument

```

**Comment by ngiger** [comment]
I can avoid this error if I replace line 140 in src/model/atcclass.rb
`-                       @sequences.collect { |seq| seq.packages.values }.flatten`
by
```
+                       found = []
+                       @sequences.each do |seq| if seq.packages.is_a?(Hash) then  found << seq.packages.values  end; end
+                       found.flatten!

```

**Comment by ngiger** [comment]
I think the problem stems from a wrong index. Trying to rebuild all indices with atc
 `bundle exec ruby jobs/rebuild_indices atc_index sequence_index_atc atc_index_company substance_index_atc indication_index_atc_de indication_index_atc_fr atcless`
 Then restarting rackup and checking again.

**Comment by zdavatz** [comment]
Just commit your patch and we can test that. No further digging needed.

**Comment by ngiger** [comment]
No because with my patch, I still have an error when I access `/de/gcc/patinfo/reg/68792/seq/01/pack/001`

**Comment by ngiger** [comment]
Executed the following commands in `bin/admin`
` registration('68792').packages.size{ |pack| pack.patinfo = nil; pack.odba_isolated_store }`
`registration('68792').each_sequence{ |seq| seq.patinfo = nil; seq.odba_isolated_store }`
And reparsed the PI 68792 again. Now the PI display correctly

**Comment by zdavatz** [comment]
seems to work without bin/admin commands.
