### ISSUE TITLE
7680004880025, Hepatect, Impfstoff/Blutprodukt hat SB und SL Eintrag, auf oddb.org aber nicht.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#250]
1. Warum hat dieses Produkt keinen Preis?
2. https://generika.cc/de/generika/show/reg/00488/seq/02/pack/002
3. Es ist in der SL:
4. <img width="547" alt="Bildschirmfoto 2024-02-20 um 09 31 09" src="https://github.com/zdavatz/oddb.org/assets/4953/659dc14c-2d66-4228-87af-25b0e17a476e">

**Comment by ngiger** [comment]
Die Felder deductible, ikscat, sl_generic_type und narcotic vom BSV-XML wurden nicht richtig übernommen. Tests dafür gemacht.
Werden aber nicht die Felder ikscat und narcotic (aka bm_flag) vom plugin/narcotics.rb gesetzt. Wann läuft jobs/update_narcotics und mit welchem Parameter?
Schaue jetzt, ob der Preis richtig aufdatiert wird.

**Comment by zdavatz** [comment]
IKS Cat kommt von der Swissmedic Packungen Datei.

**Comment by ngiger** [comment]
Problem is that getting the package with  `<SwissmedicNo8>488001</SwissmedicNo8>` returns nil, as it expects `00488001`. Therefore we must expand it with something like `sprintf('%08i', s1.to_i)`

**Comment by ngiger** [comment]
Found another problem. Registration 66715 has package 001 but it does not show up in oddb.org and is not created when found by bsv_xml importer

```
grep 'SwissmedicNo8>66715' data/xml/Preparations.xml 
        <SwissmedicNo8>66715001</SwissmedicNo8>
        <SwissmedicNo8>66715003</SwissmedicNo8>
        <SwissmedicNo8>66715005</SwissmedicNo8>
        <SwissmedicNo8>66715004</SwissmedicNo8>
        <SwissmedicNo8>66715006</SwissmedicNo8>

```

**Comment by ngiger** [comment]
Cleaned up the code for the price changes. The problem that IKSNR with leading 0 are not parsed is fixed. This did not work for a long time. 
May be the change in commit 990ef52a9187bd7b21694367f2588a3c409ee91c by me in 2015 `Remove pharmacode from bsv-import`
where `@pack ||= @app.package_by_ikskey(@text)` was replaced by `@pack ||= @app.package_by_ikskey(@text)`
led to this problem.
Or the BSV-XML contained before the leading 0 in the field `SwissmedicNo8`
Anyway. I added a test case which checks this case.
