### ISSUE TITLE
FI images are missing

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#254]
The images in the FI are missing here: https://ch.oddb.org/de/gcc/fachinfo/reg/57141

**Comment by ngiger** [comment]
Looks like we have a confusing with the path name. It could be found under
`/resources/images/fi/de/57141Leuprorelin_Sandoz_3_Monate__Fertigspritze_mit_Implantat_files/1.png
`
But is referenced as
 `/resources/images/fi/de/Leuprorelin_Sandoz_3_Monate__Implantat_files/1.png`

**Comment by zdavatz** [comment]
Yes, the image is here: 

https://ch.oddb.org/resources/images/fi/de/57141Leuprorelin_Sandoz_3_Monate__Fertigspritze_mit_Implantat_files/1.png

so why does it not work?

**Comment by ngiger** [comment]
The emitted path is` /resources/images/fi/de/Leuprorelin_Sandoz_3_Monate__Implantat_files/1.png`

**Comment by zdavatz** [comment]
why is the path wrong?

**Comment by ngiger** [comment]
Probably because auf https://github.com/zdavatz/oddb.org/commit/2f7a71466b21d190371b9a192294eac908a653bc
But unfortunately no unit test checked the correct image path

**Comment by ngiger** [comment]
In the above mentioned the variable image_folder was not passed to parse_fachinfo_html.
Also I think we should simplify the name of the image_folder like this:

1. FI: iksnr
2. PI: iksnr-ikscd 

If you like the name we could just use the first 10 letters for me.

**Comment by ngiger** [comment]
Fixed the problem.

- Improved the log-messages a little bit
- Only create a directory under images, when there is really a image to store
- Use parameter image_folder to ensure consistency between fiparse daemon and importer
- Removed parameter format from `parse_patinfo_html` and `parse_fachinfo_html` as it is always :swissmedicinfo
- Cleanup fiparse and unit tests
- Images go now under `doc/resources/images/fi/de/<iksnr>_<first 10 chars of name>`

**Comment by zdavatz** [comment]
this commit seems to blow up the homepage.
![latest-screenshot](https://github.com/zdavatz/oddb.org/assets/4953/fe7f4684-1af0-4c12-bd1e-8010d47dbb33)

**Comment by zdavatz** [comment]
![latest-screenshot](https://github.com/zdavatz/oddb.org/assets/4953/0c59aa43-405f-42a5-b97d-876c4226d50b)

**Comment by zdavatz** [comment]
Problem happens with the parsing of these Products:
 52412 ["de"] ATG-Fresenius
  52412 ["fr"] ATG-Fresenius
  53831 ["de"] Plaquenil
  53831 ["fr"] Plaquenil
  54868 ["de"] Zeffix
  54868 ["fr"] Zeffix
  61385 ["de"] Pradaxa 110 mg
  61385 ["fr"] Pradaxa 110 mg
  62235 ["de"] Clorazepate Zentiva 20 mg
  62235 ["fr"] Clorazepate Zentiva 20 mg
  62321 ["de"] Candesartan HCT Zentiva 8/12.5mg
  62321 ["fr"] Candesartan HCT Zentiva 8/12.5mg
  62960 ["de"] Escitalopram Zentiva 10 mg
  62960 ["fr"] Escitalopram Zentiva 10 mg
  68472 ["de"] Levodopa / Benserazid Devatis 62.5 mg (50 mg + 12.5 mg)
  68472 ["fr"] Levodopa / Benserazid Devatis 62.5 mg (50 mg + 12.5 mg)
  68502 ["de"] Zenon 10 mg/10 mg
  68502 ["fr"] Zenon 10 mg/10 mg

**Comment by ngiger** [comment]
Homepage is working fine here. Did you reparse manually some FIs? Or was it import_daily?

**Comment by zdavatz** [comment]
Import_daily ran as usual.

**Comment by zdavatz** [comment]
PI titles also no longer work:

![latest-screenshot](https://github.com/zdavatz/oddb.org/assets/4953/b110507b-5d1c-4516-a716-4c6e9af4b3cc)

**Comment by ngiger** [comment]
When I look at view-source:https://ch.oddb.org/de/gcc/fachinfo/reg/52412
I see the reference to the image as `IMG src="[/resources/images/fi/de/p_margin_top_0pt_margin_right_0pt_margin_bottom_0pt_margin_left_0pt__table_border_spacing_0pt_border_files/1.png](view-source:https://ch.oddb.org/resources/images/fi/de/p_margin_top_0pt_margin_right_0pt_margin_bottom_0pt_margin_left_0pt__table_border_spacing_0pt_border_files/1.png)"`
Whereas on my test server I find under view-source:http://localhost:8012/de/gcc/fachinfo/reg/52412
`IMG src="[/resources/images/fi/de/52412_Grafalon/1.png](view-source:http://localhost:8012/resources/images/fi/de/52412_Grafalon/1.png)"`
My question is: Did you restart the services for fiparse after you pulled the changes? If not this explain the error.

**Comment by ngiger** [comment]
In general, after pulling a PR you should restart **_ALL_** services/ch.oddb*

**Comment by zdavatz** [comment]
Ok, this works for PI and FI. The `fiparse` process had to be restarted, before reparsing.
