### ISSUE TITLE
Import_Swissmedic läuft nicht mehr

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#265]
1. bundle exec ruby jobs/import_swissmedic
2. results in
```
2024-03-07 10:48:32 +0100: /var/www/oddb.org/src/model/epha_interaction.rb:67:in `read_from_csv': Took 3 seconds to load /var/www/oddb.org/data/csv/interacti
ons_de_utf8.csv                                                                                                                                              
/var/www/oddb.org/log/job.pid is deleted
/var/www/oddb.org/src/plugin/swissmedic.rb:81:in `initialize': undefined method `attributes' for nil:NilClass (NoMethodError)

      @@gpreparations_url = BASE_URL + doc.xpath("//a").find{|x| /Erweiterte Arzneimittelliste/.match(x.children.text) }.attributes['href'].value
                                                                                                                        ^^^^^^^^^^^
        from /var/www/oddb.org/src/util/updater.rb:373:in `new'
        from /var/www/oddb.org/src/util/updater.rb:373:in `update_swissmedic'
        from jobs/import_swissmedic:14:in `block in <module:Util>'
        from /var/www/oddb.org/src/util/job.rb:40:in `run'
        from jobs/import_swissmedic:12:in `<module:Util>'
        from jobs/import_swissmedic:11:in `<module:ODDB>'
        from jobs/import_swissmedic:10:in `<main>'
```

**Comment by ngiger** [comment]
Der Import via `bundle exec ruby jobs/import_swissmedic` lief bei mir am 27.2.24 ohne Probleme durch.
Muss mal schauen, ob sich im https://www.swissmedic.ch/swissmedic/de/home/services/listen_neu.html was geändert hat.

**Comment by zdavatz** [comment]
Lief er bei Dir mit allen Followern durch? Es gab nach dem 27.2. noch Änderungen, soviel ich weiss.

**Comment by ngiger** [comment]
Die Links für "Zugelassene Packungen" und "Zugelassene Co-Marketing-Humanarzneimittel" stimme noch.

**Comment by zdavatz** [comment]
Das ist der Direktlink, siehe: https://github.com/zdavatz/cpp2sqlite/blob/master/scripts/download.sh#L70

der hat sich nicht geändert.

**Comment by ngiger** [comment]
Via https://www.swissmedic.ch/swissmedic/de/home/suche.html#Erweiterte%20Arzneimittelliste finde ich 
[Erweiterte Arzneimittel mit Indikation XLSX, 2 MB, 29.02.2024](https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/erweiterte_ham.xlsx.download.xlsx/Erweiterte_Arzneimittelliste%20HAM.xlsx)
Aber dieser Link ist in keiner Inhaltseite mehr zu finden. Also hat swissmedic hier was geändert. Aber man könnte obigen Link direkt nutzen. Probier mal aus ob das läuft

**Comment by zdavatz** [comment]
Der Link ist hier vorhanden: https://www.swissmedic.ch/swissmedic/de/home/services/listen_neu.html#-257211596

**Comment by ngiger** [comment]
Okay. Der Name wurde von "Erweiterte Arzneimittelliste" auf "Erweiterte Arzneimittel mit Indikation" geändert
