### ISSUE TITLE
import_bsv Error odba_id=55257061

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#287]
Plugin: ODDB::BsvXmlPlugin

Error: NoMethodError
Message: undefined method `same_as?' for #<ODDB::PatinfoDocument:0x00007efd2df8b7c8 @packages=#<ODBA::Stub:5668080#55383413 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @distribution=nil, @revision=2024-11-12 10:18:18.109255876 +0100, @fabrication=nil, @iksnrs=#<ODBA::Stub:5668100#55383414 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @odba_observers=[], @odba_id=55257061, @name=#<ODBA::Stub:5668120#55383415 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @galenic_form=nil, @effects=#<ODBA::Stub:5668140#55383416 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @date=#<ODBA::Stub:5668160#55383417 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @amendments=nil, @usage=#<ODBA::Stub:5668180#55383418 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @contra_indications=#<ODBA::Stub:5668200#55383419 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @precautions=#<ODBA::Stub:5668220#55383420 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @odba_persistent=true, @pregnancy=#<ODBA::Stub:5668240#55383421 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @oid=55257061, @unwanted_effects=#<ODBA::Stub:5668260#55383422 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @odba_prefetch=nil, @general_advice=#<ODBA::Stub:5668280#55383423 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @company=#<ODBA::Stub:5668300#55383424 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>, @composition=#<ODBA::Stub:5668320#55383425 @odba_class=ODDB::Text::Chapter @odba_container=5668040#55257061>>

**Comment by zdavatz** [comment]
Trying these:
1. `ODBA.cache.fetch(55257061, nil).class` -> `-> ODDB::PatinfoDocument`
2. `system = ODBA.cache.fetch_named('oddbapp', self) {OddbPrevalence.new}` -> `#<OddbPrevalence:0x00007ffaae339d88>`
3. `system.odba_store` -> `#<OddbPrevalence:0x00007ffad7ce6650>`
4.

**Comment by zdavatz** [comment]
```
Plugin: ODDB::BsvXmlPlugin

Error: NoMethodError
Message: undefined method `same_as?' for #<ODDB::PatinfoDocument:0x00007f4ea02a9310 @packages=#<ODBA::Stub:5668800#55383427 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @distribution=nil, @revision=2024-11-12 10:18:21.97892103 +0100, @fabrication=nil, @iksnrs=#<ODBA::Stub:5668820#55383428 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @odba_observers=[], @odba_id=55257062, @name=#<ODBA::Stub:5668840#55383429 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @galenic_form=nil, @effects=#<ODBA::Stub:5668860#55383430 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @date=#<ODBA::Stub:5668880#55383431 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @amendments=#<ODBA::Stub:5668900#55383432 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @usage=#<ODBA::Stub:5668920#55383433 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @contra_indications=#<ODBA::Stub:5668940#55383434 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @precautions=#<ODBA::Stub:5668960#55383435 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @odba_persistent=true, @pregnancy=#<ODBA::Stub:5668980#55383436 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @oid=55257062, @unwanted_effects=#<ODBA::Stub:5669000#55383437 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @odba_prefetch=nil, @general_advice=#<ODBA::Stub:5669020#55383438 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @company=#<ODBA::Stub:5669040#55383439 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>, @composition=#<ODBA::Stub:5669060#55383440 @odba_class=ODDB::Text::Chapter @odba_container=5668760#55257062>>
```

**Comment by ngiger** [comment]
Okay now I see in the debugger after having placed in src/model/patinfo.rb the proc same_as? for PatinfoDocument
```
+    def same_as?(patinfo)
+      binding.pry
+    end
```
Running jobs/import_bsv gets now
```
Byebug::Context

From: /var/www/oddb.org/src/model/patinfo.rb:71 ODDB::PatinfoDocument#same_as?:

    69: def same_as?(patinfo)
    70:   binding.pry
 => 71: end

[1] pry(#<ODDB::PatinfoDocument>)> self.odba_id
=> 55257061
[2] pry(#<ODDB::PatinfoDocument>)> backtrace
--> #0  ODDB::PatinfoDocument.same_as?(patinfo#String) at /var/www/oddb.org/src/model/patinfo.rb:71
    #1  ODBA::Stub.method_missing(meth_symbol#Symbol, *args#Array, &block#NilClass) at /var/www/ruby/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:115
    #2  block in ODDB::Composition.block in active_agent(substance_or_oid#String) at /var/www/oddb.org/src/model/composition.rb:47
    ͱ-- #3  Array.each at /var/www/ruby/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:115
    ͱ-- #4  Enumerable.find(*args) at /var/www/ruby/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:115
    #5  ODBA::Stub.method_missing(meth_symbol#Symbol, *args#Array, &block#Proc) at /var/www/ruby/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:115
    #6  ODDB::Composition.active_agent(substance_or_oid#String) at /var/www/oddb.org/src/model/composition.rb:47
    #7  ODBA::Stub.send(*args#Array) at /var/www/oddb.org/(eval):2
    #8  block in ODDB::Persistence::Pointer.block in resolve(hook#ODDB::Composition) at /var/www/oddb.org/src/util/persistence.rb:312
    ͱ-- #9  Array.each at /var/www/oddb.org/src/util/persistence.rb:302
    #10 ODDB::Persistence::Pointer.resolve(hook#ODDB::Composition) at /var/www/oddb.org/src/util/persistence.rb:302
    #11 ODDB::Persistence::Pointer.issue_create(app#OddbPrevalence) at /var/www/oddb.org/src/util/persistence.rb:226
    #12 block in OddbPrevalence.block in create(pointer#ODDB::Persistence::Pointer) at /var/www/oddb.org/src/util/oddbapp.rb:114
    #13 ODDB::Failsafe.failsafe(klass#Class, failval#Symbol, &block#Proc) at /var/www/oddb.org/src/util/failsafe.rb:10
    #14 OddbPrevalence.create(pointer#ODDB::Persistence::Pointer) at /var/www/oddb.org/src/util/oddbapp.rb:113
    #15 block in ODDB::Persistence::Pointer.block in resolve(hook#OddbPrevalence) at /var/www/oddb.org/src/util/persistence.rb:312
    ͱ-- #16 Array.each at /var/www/oddb.org/src/util/persistence.rb:302
    #17 ODDB::Persistence::Pointer.resolve(hook#OddbPrevalence) at /var/www/oddb.org/src/util/persistence.rb:302
    #18 ODDB::Persistence::Pointer.issue_update(hook#OddbPrevalence, values#Hash, origin#NilClass) at /var/www/oddb.org/src/util/persistence.rb:274
    #19 block in OddbPrevalence.block in update(pointer#ODDB::Persistence::Pointer, values#Hash, origin#NilClass) at /var/www/oddb.org/src/util/oddbapp.rb:135
    #20 ODDB::Failsafe.failsafe(klass#Class, failval#NilClass, &block#Proc) at /var/www/oddb.org/src/util/failsafe.rb:10
    #21 OddbPrevalence.update(pointer#ODDB::Persistence::Pointer, values#Hash, origin#NilClass) at /var/www/oddb.org/src/util/oddbapp.rb:133
    #22 ODDB::App.update(pointer#ODDB::Persistence::Pointer, values#Hash, origin#NilClass) at /var/www/oddb.org/src/util/oddbapp.rb:1597
    #23 block in ODDB::BsvXmlPlugin::PreparationsListener.block in add_bag_composition_to_sequence(sequence#ODDB::Sequence, substances#Array) at /var/www/oddb.org/src/plugin/bsv_xml.rb:277
    ͱ-- #24 Array.each at /var/www/oddb.org/src/plugin/bsv_xml.rb:269
    #25 ODDB::BsvXmlPlugin::PreparationsListener.add_bag_composition_to_sequence(sequence#ODDB::Sequence, substances#Array) at /var/www/oddb.org/src/plugin/bsv_xml.rb:269
    #26 ODDB::BsvXmlPlugin::PreparationsListener.tag_end(name#String) at /var/www/oddb.org/src/plugin/bsv_xml.rb:420
    #27 REXML::Parsers::StreamParser.parse at /var/www/ruby/3.2.0/gems/rexml-3.3.2/lib/rexml/parsers/streamparser.rb:36
    #28 #<Class:REXML::Document>.parse_stream(source#StringIO, listener#ODDB::BsvXmlPlugin::PreparationsListener) at /var/www/ruby/3.2.0/gems/rexml-3.3.2/lib/rexml/document.rb:402
    #29 ODDB::BsvXmlPlugin.update_preparations(io#Zip::InputStream, opts#Hash) at /var/www/oddb.org/src/plugin/bsv_xml.rb:1099
    #30 block (2 levels) in ODDB::BsvXmlPlugin.block (2 levels) in _update(path#String) at /var/www/oddb.org/src/plugin/bsv_xml.rb:782
    #31 Zip::Entry.get_input_stream(&block#Proc) at /var/www/ruby/3.2.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:540
    #32 block in ODDB::BsvXmlPlugin.block in _update(path#String) at /var/www/oddb.org/src/plugin/bsv_xml.rb:782
    #33 block in Zip::EntrySet.block in each at /var/www/ruby/3.2.0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:38
    ͱ-- #34 Hash.each at /var/www/ruby/3.2.0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:37
    #35 Zip::EntrySet.each at /var/www/ruby/3.2.0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:37
    #36 Zip::CentralDirectory.each(&a_proc#Proc) at /var/www/ruby/3.2.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:185
    #37 block in #<Class:Zip::File>.block in foreach(zip_file_name#String, &block#Proc) at /var/www/ruby/3.2.0/gems/rubyzip-2.3.2/lib/zip/file.rb:173
    #38 #<Class:Zip::File>.open(file_name#String, create#FalseClass, options#Hash) at /var/www/ruby/3.2.0/gems/rubyzip-2.3.2/lib/zip/file.rb:125
    #39 #<Class:Zip::File>.foreach(zip_file_name#String, &block#Proc) at /var/www/ruby/3.2.0/gems/rubyzip-2.3.2/lib/zip/file.rb:172
    #40 ODDB::BsvXmlPlugin._update(path#String) at /var/www/oddb.org/src/plugin/bsv_xml.rb:778
    #41 ODDB::BsvXmlPlugin.update at /var/www/oddb.org/src/plugin/bsv_xml.rb:773
    #42 block in ODDB::Updater.block in update_bsv at /var/www/oddb.org/src/util/updater.rb:269
    #43 ODDB::Updater.wrap_update(klass#Class, subj#String, &block#Proc) at /var/www/oddb.org/src/util/updater.rb:483
    #44 ODDB::Updater.update_bsv at /var/www/oddb.org/src/util/updater.rb:267
    #45 block in block in <module:Util> at /var/www/oddb.org/jobs/import_bsv:14
    #46 #<Class:ODDB::Util::Job>.run(opts#Hash, &block#Proc) at /var/www/oddb.org/src/util/job.rb:40
    #47 <module:Util> at /var/www/oddb.org/jobs/import_bsv:12
    #48 <module:ODDB> at /var/www/oddb.org/jobs/import_bsv:11
    #49 <main> at /var/www/oddb.org/jobs/import_bsv:10

From: /var/www/oddb.org/src/model/patinfo.rb:71 ODDB::PatinfoDocument#same_as?:



twice up
2] pry(#<ODDB::ActiveAgent>)> up

From: /var/www/oddb.org/src/model/composition.rb:47 ODDB::Composition#active_agent:

    46: def active_agent(substance_or_oid)
 => 47:   active_agents.find { |active| active.same_as?(substance_or_oid) }
    48: end

[2] pry(#<ODDB::Composition>)> substance_or_oid
=> "Lamivudinum"
[3] pry(#<ODDB::Composition>)> self.odba_id
=> 50394914
[6] pry(#<ODDB::Composition>)> self.sequence.iksnr
=> "53662"
[7] pry(#<ODDB::Composition>)> self.sequence.seqnr
=> "01"
```

Verifiying that ch.oddb.org has problems displaying this registratrion I visited https://ch.oddb.org/de/gcc/search/zone/drugs/search_query/53662/search_type/st_registration?
And did see an error like 

```
/var/www/oddb.org/src/view/admin/sequence.rb: in block in initialize
        components.delete([1,0]) unless model.find{ |x| x.dose && x.dose.qty != 0 }
```

**Comment by ngiger** [comment]
ch.oddb> registration('53662').sequence('01').basename
-> 3TC

**Comment by zdavatz** [comment]
Ok, this is one of the PRs where we add the substance from the BSV XML: https://github.com/zdavatz/oddb.org/pull/173

**Comment by zdavatz** [comment]
now getting

Plugin: ODDB::BsvXmlPlugin

Error: RuntimeError
Message: entity expansion has grown too large
Backtrace:
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rexml-3.3.3/lib/rexml/parsers/baseparser.rb:559:in `block in unnormalize'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rexml-3.3.3/lib/rexml/parsers/baseparser.rb:551:in `each'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rexml-3.3.3/lib/rexml/parsers/baseparser.rb:551:in `unnormalize'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rexml-3.3.3/lib/rexml/parsers/streamparser.rb:39:in `parse'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rexml-3.3.3/lib/rexml/document.rb:402:in `parse_stream'
/var/www/oddb.org/src/plugin/bsv_xml.rb:1098:in `update_preparations'
/var/www/oddb.org/src/plugin/bsv_xml.rb:781:in `block (2 levels) in _update'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rubyzip-2.3.2/lib/zip/entry.rb:540:in `get_input_stream'
/var/www/oddb.org/src/plugin/bsv_xml.rb:781:in `block in _update'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:38:in `block in each'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:37:in `each'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rubyzip-2.3.2/lib/zip/entry_set.rb:37:in `each'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rubyzip-2.3.2/lib/zip/central_directory.rb:185:in `each'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rubyzip-2.3.2/lib/zip/file.rb:173:in `block in foreach'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rubyzip-2.3.2/lib/zip/file.rb:125:in `open'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/rubyzip-2.3.2/lib/zip/file.rb:172:in `foreach'
/var/www/oddb.org/src/plugin/bsv_xml.rb:777:in `_update'
/var/www/oddb.org/src/plugin/bsv_xml.rb:772:in `update'
/var/www/oddb.org/src/util/updater.rb:269:in `block in update_bsv'
/var/www/oddb.org/src/util/updater.rb:483:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:267:in `update_bsv'
jobs/import_bsv:14:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_bsv:12:in `<module:Util>'
jobs/import_bsv:11:in `<module:ODDB>'
jobs/import_bsv:10:in `<main>'

**Comment by zdavatz** [comment]
Seems to be related to: https://github.com/ruby/rexml/issues/198

**Comment by zdavatz** [comment]
https://github.com/zdavatz/oddb.org/pull/279
