### ISSUE TITLE
HTTPS encrypted 

### ISSUE THREAD

**Issue by AnBuKu** [zdavatz/oddb.org#54]
Secure oddb.org web site with SSL for secure connection and authentication.

It might be wise and responsible to update oddb.org to HTTPS. Thus, medical practitioners and their patients will be more secure and enjoy more privacy due to encrypted connection from their browser to oddb.org. - In other words: ["The main motivation for HTTPS is authentication of the visited website and protection of the privacy and integrity of the exchanged data](https://en.wikipedia.org/wiki/HTTPS)" (source: en.wikipedia.org).

As well, server certificates are available at 0 costs from reliable sources today, e.g. [let's encrypt](https://letsencrypt.org/). So, maybe during the next server update? :-)

**Comment by zdavatz** [comment]
Sure, this is always an option.
