### ISSUE TITLE
doctors import ergibt einen Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#58]
```
Plugin: ODDB::Doctors::RefdataNatPlugin

Error: Encoding::CompatibilityError
Message: incompatible character encodings: UTF-8 and US-ASCII
Backtrace:
/var/www/oddb.org/src/plugin/refdata_nat.rb:247:in `block in store_doctor'
/var/www/oddb.org/src/plugin/refdata_nat.rb:242:in `each'
/var/www/oddb.org/src/plugin/refdata_nat.rb:242:in `store_doctor'
/var/www/oddb.org/src/plugin/refdata_nat.rb:345:in `block in parse_xml'
/var/www/oddb.org/src/plugin/refdata_nat.rb:299:in `each'
/var/www/oddb.org/src/plugin/refdata_nat.rb:299:in `each_with_index'
/var/www/oddb.org/src/plugin/refdata_nat.rb:299:in `parse_xml'
/var/www/oddb.org/src/plugin/refdata_nat.rb:112:in `update'
/var/www/oddb.org/src/util/updater.rb:271:in `block in update_refdata_nat'
/var/www/oddb.org/src/util/updater.rb:532:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:269:in `update_refdata_nat'
jobs/import_refdata_nat:14:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_refdata_nat:12:in `<module:Util>'
jobs/import_refdata_nat:11:in `<module:ODDB>'
jobs/import_refdata_nat:10:in `<main>'
```

**Comment by ngiger** [comment]
Ich habe heute auf thinpower src/plugin/refdata_nat.rb so modifiziert, dass ich diese Ausnahme im pry hätte begutachten können.

Dann konnte ich im screen debug_refdata_nat den Befehl

> sudo -u apache bundle-250 exec ruby-250 jobs/import_refdata_nat 

Ohne Probleme laufen lassen können.

Mir scheint, dass das Problem in diesem Fall behoben ist.

**Comment by zdavatz** [comment]
This error is back with things like this:
`<DESCR2>Hal–k</DESCR2>
<STRNO>1–3</STRNO>`

**Comment by zdavatz** [comment]
[out.txt](https://github.com/zdavatz/oddb.org/files/2471945/out.txt)
I narrowed it down with
1. grep --color='auto' -P -n "[^\x00-\x7F]" >> out.xml
2. g/í/d and all the other special characters.

**Comment by zdavatz** [comment]
`sed -n 'l' partner.xml` could also be useful.

**Comment by zdavatz** [comment]
Looks like we have 'en dash (–)' in the file.

**Comment by zdavatz** [comment]
Useful conversion tool: https://r12a.github.io/app-conversion/

**Comment by ngiger** [comment]
The import finished without problem on oddb-ci2.
Looks like refdata fixed the problem as there is no STRNO line present in latest partner.xml.
Rerunning import on thinpower

**Comment by zdavatz** [comment]
This error is back per 11.11.2018: https://mail.google.com/mail/u/0/#inbox/WhctKJVBDfnVJhTnPtnsrQjRmvJTvssznhfNnDcWKBzQpgzSNZMtgjpXTPpSXqQzxqHCdrv

**Comment by zdavatz** [comment]
Ich denke es ist entweder ein EM-Dash oder ein EN-Dash, welcher das Problem macht.

**Comment by zdavatz** [comment]
[out.txt](https://github.com/zdavatz/oddb.org/files/2571349/out.txt)

"Affoltern am Albis" sieht sehr verdächtig aus. Siehe begefügtes File.

**Comment by ngiger** [comment]
Ich habe mal einfach diesen Workaround gepushed, mit dem gestern der import durchlief.

**Comment by zdavatz** [comment]
Danke!
