### ISSUE TITLE
SL Error Update

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#60]
Plugin: ODDB::BsvXmlPlugin

Error: NoMethodError
Message: undefined method `update_g_l__d_i_f_f__s_b_' for #<ODDB::BsvXmlPlugin:0x00007f8a480e8ec0>
Did you mean?  update_g_l__diff__s_b
Backtrace:
/var/www/oddb.org/src/plugin/bsv_xml.rb:612:in `block (2 levels) in _update'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.2.1/lib/zip/entry.rb:501:in `get_input_stream'
/var/www/oddb.org/src/plugin/bsv_xml.rb:612:in `block in _update'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.2.1/lib/zip/entry_set.rb:38:in `block in each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.2.1/lib/zip/entry_set.rb:37:in `each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.2.1/lib/zip/entry_set.rb:37:in `each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.2.1/lib/zip/central_directory.rb:182:in `each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.2.1/lib/zip/file.rb:149:in `block in foreach'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.2.1/lib/zip/file.rb:101:in `open'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.2.1/lib/zip/file.rb:148:in `foreach'
/var/www/oddb.org/src/plugin/bsv_xml.rb:607:in `_update'
/var/www/oddb.org/src/plugin/bsv_xml.rb:602:in `update'
/var/www/oddb.org/src/util/updater.rb:301:in `block in update_bsv'
/var/www/oddb.org/src/util/updater.rb:532:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:299:in `update_bsv'
/var/www/oddb.org/src/util/updater.rb:219:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'

**Comment by ngiger** [comment]
Previous content was:

> unzip -t /var/www/oddb.org/data/xml/XMLPublications-2018.01.23.zip 
Archive:  /var/www/oddb.org/data/xml/XMLPublications-2018.01.23.zip
    testing: Gestrichene_Packungen_Emballages_radies.xls   OK
    testing: GL_Diff_SB.xml           OK
    testing: ItCodes.xml              OK
    testing: PR160501.txt             OK
    testing: PR160601.txt             OK
    testing: PR160701.txt             OK
    testing: PR160801.txt             OK
    testing: PR160901.txt             OK
    testing: Preparations.xml         OK
    testing: Publications.xls         OK
No errors detected in compressed data of /var/www/oddb.org/data/xml/XMLPublications-2018.01.23.zip.

new content is:
> zip -t /var/www/oddb.org/data/xml/XMLPublications-2018.05.01.zip
Archive:  /var/www/oddb.org/data/xml/XMLPublications-2018.05.01.zip
    testing: ItCodes.xml              OK
    testing: GL_DIFF_SB.xml           OK
    testing: Preparations.xml         OK
    testing: Publications.xlsx        OK
    testing: Gestrichene_Packungen_Emballages_radies.xlsx   OK
No errors detected in compressed data of /var/www/oddb.org/data/xml/XMLPublications-2018.05.01.zip.
> 

>

**Comment by zdavatz** [comment]
ok! Good to know! Another unannounced change by the BAG.

**Comment by ngiger** [comment]
Geflickt mit https://github.com/ngiger/oddb.org/commit/1ceea71f44e31c4b98c7ac81328fb872e2bd9334

Anpassung auf thinpower gepullt. Startest Du den jobs/import_bsv von Hand?

**Comment by zdavatz** [comment]
@ngiger bitte selber starten und zuerst altes File löschen.

**Comment by zdavatz** [comment]
Danke, klappt wunderbar.
