### ISSUE TITLE
AJAX für Interaktions-Suche wieder aktivieren

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#62]
Die [Interaktionen-Suche](https://ch.oddb.org/de/gcc/home_interactions/) geht zur Zeit nicht mehr, weil das AJAX deaktiviert wurde. AJAX muss für die Interaktionen und die Home-Seite [instant](https://ch.oddb.org/de/gcc/home/search_form/instant) wieder aktiviert werden. Die AJAX Mouse-Overs in Suchresultatsseiten bitte deaktiviert lassen.

**Comment by ngiger** [comment]
Auf oddb-ci2.dyndns.org geht die Interaktionssuche und die Instant Suche. Siehe https://oddb-ci2.dyndns.org/de/gcc/home/search_form/instant
Im Gegensatz zu ch.oddb.org ist der zurückgegebene HTML-Code UTF-8 und nicht ISO 8859-15 wie auf ch.oddb.org

![instant](https://user-images.githubusercontent.com/265800/40966905-0445f52a-68b2-11e8-87a7-61410148f573.png)
