### ISSUE TITLE
Ruby-Zip vulnerability

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#65]
https://github.com/zdavatz/oddb.org/network/dependencies. We need to upgrade to Version 1.2.2

**Comment by ngiger** [comment]
Fixed with https://github.com/ngiger/oddb.org/commit/4a1b20f5d59d2458d3f50a5cde7674c56c400b8a
Pulled change to thinpower and ran in /var/www/oddb.org the command "bundle-250 install"

**Comment by zdavatz** [comment]
Thank you!
