### ISSUE TITLE
Search by Pharmacode 4844640 Results in an Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#67]
Search by this Pharmacode _4844640_ on ch.oddb.org and you will receive an error.
```
NoMethodError at /de/gcc/search/zone/drugs/search_query/4844640/search_type/st_pharmacode
undefined method `introduction_date' for nil:NilClass
```

**Comment by ngiger** [comment]
Fixed with commit https://github.com/ngiger/oddb.org/commit/10f31516efc2df6f89b422c0ba36f2cb3ae11c22

Change pulled to thinpower and restarted

**Comment by zdavatz** [comment]
Danke!
