### ISSUE TITLE
import_daily läuft nach rm -f /var/www/oddb.org/data/xlsx/nomarketing-2019.01.28.xlsx nicht mehr weiter

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#71]
import_daily läuft nach rm -f /var/www/oddb.org/data/xlsx/nomarketing-2019.01.28.xlsx nicht mehr weiter

Der Job `sudo -u apache /usr/local/bin/bundle-250 exec ruby-250 jobs/update_textinfo_swissmedicinfo --target=both` läuft durch.

**Comment by ngiger** [comment]
Der import hängt im update_swissmedic_feeds. Die recalls hängen. Gibt es hier ein Problem mit HTTPS?

**Comment by ngiger** [comment]
Import hängt, da z,.B: in
https://www.swissmedic.ch/swissmedic/de/home/humanarzneimittel/marktueberwachung/qualitaetsmaengel-und-chargenrueckrufe/chargenrueckrufe/_jcr_content/par/teaserlist.content.paging-6.html?pageIndex=6
Neu Keine Ergenisse anstelle Keine Resultate drin steht

**Comment by ngiger** [comment]
Anpassungen gemacht und auf thinpower geholt

**Comment by zdavatz** [comment]
Danke!
