### ISSUE TITLE
Swissmedic hat neuen Download URL

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#72]
Der neue Download URL heisst: https://www.swissmedic.ch/swissmedic/de/home/services/listen_neu.html#-257211596

**Comment by zdavatz** [comment]
Sieht so aus, als hätte nur der Download-Link geändert.

**Comment by zdavatz** [comment]
Der Co-Marketing Link hat auch geändert.

**Comment by ngiger** [comment]
Genau. Die Links enthalten neu das Datum. Mann muss also neu die Seite https://www.swissmedic.ch/swissmedic/de/home/services/listen_neu.html parsen und dort den Link extrahieren

**Comment by ngiger** [comment]
Im Orphan gibt es eine neue Spalte F Zulassungs-status des Arzneimittels. Deshalb muss der Code zum Parsen noch angepasst werden.

**Comment by ngiger** [comment]
Im Packungen.xlsx wurden diverse Spalten umbenannt, neu spricht BAG von Arzneimittels und nicht mehr von Präparaten. 
Die Spalte S "Volldeklaration rev. AMZV umgesetzt"
wurde neu hinzugefügt

**Comment by ngiger** [comment]
Ebenfalls wurde die Anzahl Zeilen im Header von 5 auf 6 erhöht.
In oddb2xml (wo ich die besseren Test-Möglichkeiten habe) Änderungen gemacht., Spec-Tests laufen jetzt wieder alle durch.
bin/oddb2xml --log durchlaufen lassen um zu schauen, ob alles okay ist.

**Comment by ngiger** [comment]
Die alte Präparateliste.xlsx wurde in "Erweiterte Arzneimittelliste" umbenannt. Diverse Spalten wurden umbenannt (Präparat -> Arzneimittel).
Spalte Heilmittelcode ist neu H (war F)

Neu gibt es auch die Spalten 
* F: Heilmittelcode
* G:Verfahren nach Art. 14 Abs. 1 Bst. abis-quater HMG

Dann gibt es auch komische Datumseinträge wie 2021/01/13

**Comment by ngiger** [comment]
Spalte mit komischen Datum war:

65160 | 01 | Lynparza 50 mg, Kapseln | AstraZeneca AG | Synthetika | A | A | 14.01.2016 | 14.01.2016 | 13.01.2021

**Comment by zdavatz** [comment]
`Heilmittelcode` ist die Spalte wo früher auch die Tierarzneinittel gekennzeichnet waren. Die Tierarzneimittel sind jetzt in einem separaten File. Ansosten sollte die Spalte den gleichen Inhalt haben.

**Comment by zdavatz** [comment]
Was ist komisch an diesem Datum? `2021/01/13`

**Comment by ngiger** [comment]
import-Daily lief bei mir nicht durch. Werde den Fehler morgen analysieren:
Error: ArgumentError
Message: wrong number of arguments (given 0, expected 1..2)
Backtrace:
/var/www/oddb.org/src/util/persistence.rb:72:in `diff'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.5/lib/odba/stub.rb:112:in `method_missing'
/var/www/oddb.org/src/model/fachinfo.rb:183:in `block in add_change_log_item'
/var/www/oddb.org/src/model/fachinfo.rb:183:in `each'
/var/www/oddb.org/src/model/fachinfo.rb:183:in `find'
/var/www/oddb.org/src/model/fachinfo.rb:183:in `add_change_log_item'
/var/www/oddb.org/src/plugin/text_info.rb:153:in `store_fachinfo'
/var/www/oddb.org/src/plugin/text_info.rb:257:in `update_fachinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:1277:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1480:in `block in import_swissmedicinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1479:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1479:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:570:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:526:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:564:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:347:in `update_textinfo_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:210:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'

**Comment by ngiger** [comment]
import-Daily lief bei mir nicht durch. Werde den Fehler morgen analysieren:
Error: ArgumentError
Message: wrong number of arguments (given 0, expected 1..2)
Backtrace:
/var/www/oddb.org/src/util/persistence.rb:72:in `diff'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.5/lib/odba/stub.rb:112:in `method_missing'
/var/www/oddb.org/src/model/fachinfo.rb:183:in `block in add_change_log_item'
/var/www/oddb.org/src/model/fachinfo.rb:183:in `each'
/var/www/oddb.org/src/model/fachinfo.rb:183:in `find'
/var/www/oddb.org/src/model/fachinfo.rb:183:in `add_change_log_item'
/var/www/oddb.org/src/plugin/text_info.rb:153:in `store_fachinfo'
/var/www/oddb.org/src/plugin/text_info.rb:257:in `update_fachinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:1277:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1480:in `block in import_swissmedicinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1479:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1479:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:570:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:526:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:564:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:347:in `update_textinfo_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:210:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'

**Comment by ngiger** [comment]
Holte den DB-Backup von thinpower. Danach lief import_daily durch. Deshalb änderungen gepushed, auf thinpower geholt und in screen import_daily neu gestartet.

**Comment by zdavatz** [comment]
ok, Danke!

**Comment by zdavatz** [comment]
working!
