### ISSUE TITLE
Neu: Bei Datum "unbegrenzt" im Swissmedic Packungen.xlsx dieses Feld leer lassen.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#73]
Siehe: https://github.com/zdavatz/swissmedic-diff/issues/3

**Comment by ngiger** [comment]
Workaround für das Expiration-Datei gefunden:
Nach 30 Minuten habe ich beim import-daily dann folgenden Fehler

> Error: NoMethodError
Message: undefined method `same_as?' for #<ODDB::Text::Chapter:0x000055f5612f8a30>
Backtrace:
/var/www/oddb.org/src/util/oddbapp.rb:1205:in `block in search_single_substance'
/var/www/oddb.org/src/util/oddbapp.rb:1204:in `each'
/var/www/oddb.org/src/util/oddbapp.rb:1204:in `find'
/var/www/oddb.org/src/util/oddbapp.rb:1204:in `search_single_substance'
/var/www/oddb.org/src/util/oddbapp.rb:1332:in `substance'
/var/www/oddb.org/src/util/oddbapp.rb:1552:in `block in method_missing'
/var/www/oddb.org/src/util/oddbapp.rb:1551:in `synchronize'
/var/www/oddb.org/src/util/oddbapp.rb:1551:in `method_missing'
/var/www/oddb.org/src/plugin/swissmedic.rb:1402:in `update_substance'
/var/www/oddb.org/src/plugin/swissmedic.rb:926:in `block in update_compositions'
/var/www/oddb.org/src/plugin/swissmedic.rb:926:in `collect'
/var/www/oddb.org/src/plugin/swissmedic.rb:926:in `update_compositions'
/var/www/oddb.org/src/plugin/swissmedic.rb:1291:in `update_all_sequence_info'
/var/www/oddb.org/src/plugin/swissmedic.rb:1316:in `block in update_registrations'
/var/www/oddb.org/src/plugin/swissmedic.rb:1303:in `each'
/var/www/oddb.org/src/plugin/swissmedic.rb:1303:in `each_with_index'
/var/www/oddb.org/src/plugin/swissmedic.rb:1303:in `update_registrations'
/var/www/oddb.org/src/plugin/swissmedic.rb:355:in `update'
/var/www/oddb.org/src/util/updater.rb:421:in `block in update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:526:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:419:in `update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:213:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'

**Comment by ngiger** [comment]
Import-Daily lief nach einer weitere Anpassung gestern abend bei mir lokal durch. 
Heute Review der Anpassungen gemacht. Lasse test suite laufen vor dem pushen.

**Comment by zdavatz** [comment]
should be done with: 97bf66609f49ec878dcad307a74c6ca00244ce38
