### ISSUE TITLE
Remsima schmeisst einen Error wenn man eingeloggt ist

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#74]
1. Als Admin einloggen bei ch.oddb.org
2. Folgenden Link anklicken: https://ch.oddb.org/de/gcc/show/reg/65373/seq/01/pack/001
3. Error
![Remsima](https://user-images.githubusercontent.com/4953/54665930-bf11e580-4ae8-11e9-8daa-c6a5d49de19b.jpg)

**Comment by ngiger** [comment]
Fehler tritt bei mir lokal nicht auf, wenn ich yus auf (meine lokale) Version 1.0.5 hochziehe, welche kein Gemfile.lock mit zu alten Versionen von pg,etc  enthält, welche postgresql 10 nicht unterstützen.

**Comment by ngiger** [comment]
pg et al kamen via odba hinzu. Deshalb in yus.gemspec die Abhängigkeit wie folgt 

>  spec.add_dependency 'odba', '>= 1.1.6'

definiert

**Comment by ngiger** [comment]
Kann das Gem nicht releasen, da bei mir folgender Fehler kommt:

> yus 1.0.5 built to pkg/yus-1.0.5.gem.
Tagged v1.0.5.
Pushed git commits and tags.
rake aborted!
ERROR:  While executing gem ... (NoMethodError)
    undefined method `downcase' for nil:NilClass
Pushing gem to rubygems.org...
/home/niklaus/.rbenv/versions/2.5.0/bin/bundle:23:in `load'
/home/niklaus/.rbenv/versions/2.5.0/bin/bundle:23:in `<main>'
Tasks: TOP => release => release:rubygem_push
(See full trace by running task with --trace)

**Comment by zdavatz** [comment]
braucht yus Ruby 2.5.0?

**Comment by ngiger** [comment]
Wir haben yus auf Ruby 2.5 hochgezogen. Auf thinpower

>ps -ef | grep yus
apache    1805 15427  0 13:09 ?        00:00:31 /usr/local/bin/ruby-250 /usr/local/ruby-2.5.0/bin/yusd

**Comment by zdavatz** [comment]
ok, ich muss zuerst noch dieses Problem lösen:
```
~/.software/yus> gem install pg -v '1.1.4' --source 'https://rubygems.org/'
Building native extensions. This could take a while...
ERROR:  Error installing pg:
	ERROR: Failed to build gem native extension.

    current directory: /home/zeno/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pg-1.1.4/ext
/home/zeno/.rbenv/versions/2.5.0/bin/ruby -r ./siteconf20190321-28156-1q6tw92.rb extconf.rb
checking for pg_config... no
No pg_config... trying anyway. If building fails, please try again with
 --with-pg-config=/path/to/pg_config
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
```

**Comment by ngiger** [comment]
Pfad dürfte etwa so lauten /usr/local/pg-10_1/bin/pg_config (auf thinpower). Dort wo Du Postgresql 10 installiert hast

**Comment by zdavatz** [comment]
Dein gemspec hat noch einen Fehler: 
```
~/.software/yus> gem push pkg/yus-1.0.5.gem
Pushing gem to https://rubygems.org...
ERROR:  "https://rubygems.org" is not allowed by the gemspec, which only allows "rubygems.org"
```

**Comment by zdavatz** [comment]
Ok, released.

**Comment by zdavatz** [comment]
siehe: 0579ca06b37b5a7961a0539f3cf88bafdc4d9c33

**Comment by ngiger** [comment]
Ich habe die Gem pg, odba, yus und verwandte hochgezogen. Jetzt bekomme ich immer noch den gleichen Fehler wenn ich eingeloggt bin.
Wenn ich NICHT eingeloggt bin, habe ich folgenden UTF-8 Fehler (der bei mir lokal nicht auftritt).

> ArgumentError at /de/gcc/show/reg/65373/seq/01/pack/001
invalid byte sequence in US-ASCII
Ruby 	/var/www/oddb.org/vendor/ruby/2.5.0/gems/htmlgrid-1.1.4/lib/htmlgrid/component.rb: in gsub, line 226
Web 	GET ch.oddb.org/de/gcc/show/reg/65373/seq/01/pack/001
Traceback (innermost first)
    /var/www/oddb.org/vendor/ruby/2.5.0/gems/htmlgrid-1.1.4/lib/htmlgrid/component.rb: in gsub
        				value.to_s.gsub(@@nl2br_ptrn, '<br>')...
    /var/www/oddb.org/vendor/ruby/2.5.0/gems/htmlgrid-1.1.4/lib/htmlgrid/component.rb: in _to_html
        				value.to_s.gsub(@@nl2br_ptrn, '<br>')

Werde thinpower DB dumpen und lokal aufspielen zum testen

**Comment by zdavatz** [comment]
wieder ein US-ASCII errot

**Comment by ngiger** [comment]
Commit auf thinpower nachgezogen. Auf thinpower noch folgende 2 Befehle unter bin/admin ausgeführt:

> ch.oddb> companies.values.find_all { |x| !x.pointer}.each{ |company| company.pointer = ODDB::Persistence::Pointer.new([:company, company.oid]); company.odba_store}
-> Array
ch.oddb> companies.values.each{ |x| x.search_terms}
-> Array

Jetzt scheint das Problem behoben zu sein.
