### ISSUE TITLE
Remove Analysen from Code

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#77]
Remove all code related to "Analysen".

**Comment by ngiger** [comment]
Ich entferne also nicht nur Import/Exporter von analysis sondern auch alles was unter home_analysis angeboten wurde.

**Comment by zdavatz** [comment]
ja genau!

**Comment by ngiger** [comment]
Habe alles ausgebaut. Test laufen wieder fehlerfrei durch. Beim Aufstarten gibt es jedoch Probleme, da odba versucht alle Analysen-Daten zu laden und diese Klassen jetzt fehlen. Fehlermeldungen sehen wie folgt aus:

> 127.0.0.1 - - [28/May/2019:21:05:37 +0200] "GET / HTTP/1.1" 200 18359 0.0362
ArgumentError: undefined class/module ODDB::Analysis::
        /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.5/lib/odba/marshal.rb:15:in `load'
        /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.5/lib/odba/marshal.rb:15:in `load'
       <...>
        /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.5/lib/odba/cache.rb:352:in `indices'
        /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.5/lib/odba/cache.rb:458:in `retrieve_from_index'
        /var/www/oddb.org/src/state/drugs/recentregs.rb:63:in `regs_by_month'
        /var/www/oddb.org/src/state/drugs/recentregs.rb:60:in `create_package_month'
        /var/www/oddb.org/src/state/drugs/recentregs.rb:49:in `init'


Ich werde also diese Klassen im Datenmodell weiter haben. Jedoch einfach nicht mehr anzeigen.

**Comment by zdavatz** [comment]
Ok.

**Comment by ngiger** [comment]
Spec-Tests haben noch einige Fehler. Werde diese in separatem commit lösen.
Downloadliste ist schlecht. Bitte definiere, was geändert werden muss 
![grafik](https://user-images.githubusercontent.com/265800/58538323-2ccb4380-81f5-11e9-92d0-a9692114b65c.png)
