### ISSUE TITLE
ATC-Browser ist leer

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#83]
1. https://ch.oddb.org aufrufen
2. [ATC-Browser](https://ch.oddb.org/de/gcc/atc_chooser/) aufrufen.
3. ATC-Browser ist leer.

![atc-browser](https://user-images.githubusercontent.com/4953/60883503-a7eb3500-a24a-11e9-9340-46d863ba15c0.png)

**Comment by ngiger** [comment]
Reproduziert auch auf oddb-ci2.

Ein Pry-Debug auf Zeile 62 von src/view/drugs/atcchooser.rb zeigt, dass der code mit einem HTML-Leerzeichen beginnt. Ist das der Fehler?

      @model.children.first.children.first.code
      => "&nbsp;H01CB02"

Lasse mal jobs/update_atc_less laufen, um zu sehen, ob das hilft.

**Comment by zdavatz** [comment]
Interessant, woher kommt das Leerzeichen?

**Comment by ngiger** [comment]
Versuchte folgendes:

* jobs/import_whocc 
* jobs/rebuild_indices atc_index

Das brachte nix. In den Watir-Spec-Tests wird der ATC-Browser nicht getestet. Deshalb ist es für mich nicht klar, seit wann er nicht mehr funktioniert.

**Comment by zdavatz** [comment]
Lösch mal alle Cookies und den Cache von ch.oddb.org. Dann kommt immer noch
https://user-images.githubusercontent.com/4953/60883503-a7eb3500-a24a-11e9-9340-46d863ba15c0.png
wenn man ATC-Browser anklickt
![atc-browser](https://user-images.githubusercontent.com/4953/60958699-1261ab00-a307-11e9-92fb-b102313550e0.jpg)

**Comment by ngiger** [comment]
Next try is:

    atc_classes.values.find{ |x| x.code.length==0}.revision
    -> 2019-05-20 08:38:29 +0200
    ch.oddb> atc_classes.size
    -> 8092
    ch.oddb> atc_classes.delete_if { |k, v| v.code.length==0 }
    -> Hash
    ch.oddb> atc_classes.size
    -> 8091
    ch.oddb> rebuild_atc_chooser
    -> #<ODDB::AtcNode:0x00005630ef2ea3f8>
    ch.oddb> atc_classes.size
    -> 8091

This seems to fix the problem.

**Comment by ngiger** [comment]
Am 20. Mai lief ein WHO Update durch. Lasse den auf oddb-ci2 nochmals laufen, um zu sehen, ob danach der Fehler wieder auftritt, weil z.B. ein ATC-Code mit Länge 0 importiert wurde.

**Comment by ngiger** [comment]
Problem sollte mit https://github.com/ngiger/oddb.org/commit/b3f3d47894e300a442629f21bdc480a2ec2cfcd7 gefixed sein.
