### ISSUE TITLE
Upgrade nokogiri to version 1.10.4 

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#86]
Seit Mitte August meldet Github ein Security Problem bei Nokogiri.

![nokogiri](https://user-images.githubusercontent.com/4953/65137371-85735600-da09-11e9-8e28-c3f9f3798d78.png)

**Comment by zdavatz** [comment]
`/usr/local/bin/bundle-250 update nokogiri`
ergibt: 
Warning: the running version of Bundler (1.16.1) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.

**Comment by ngiger** [comment]
Dann wurde dieses Kommando schon mal ausgeführt. Verifziert mit

`/usr/local/bin/bundle-250 list nokogiri`
`/var/www/oddb.org/vendor/ruby/2.5.0/gems/nokogiri-1.10.4`

Ein Update auf die aktuelleste Version (2.0.2) von bundler ist nicht einfach möglich, da /usr/local/bin/bundle-250 Teil des lokalen Compilieren und Installieren von Ruby 2.5.0 war.

**Comment by zdavatz** [comment]
Ok! Danke. Wird geschlossen.
