### ISSUE TITLE
BAG Download Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#96]
Plugin: ODDB::BsvXmlPlugin

Error: Mechanize::ResponseCodeError
Message: 404 => Net::HTTPNotFound for https://bag.hcisolutions.ch/SL2007.Web.External/File.axd?file=XMLPublications.zip -- unhandled response
Backtrace:
/var/www/oddb.org/vendor/ruby/2.5.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:323:in `fetch'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:993:in `response_redirect'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:315:in `fetch'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'
/var/www/oddb.org/src/plugin/bsv_xml.rb:625:in `download_file'
/var/www/oddb.org/src/plugin/bsv_xml.rb:598:in `update'
/var/www/oddb.org/src/util/updater.rb:283:in `block in update_bsv'
/var/www/oddb.org/src/util/updater.rb:511:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:281:in `update_bsv'
/var/www/oddb.org/src/util/updater.rb:215:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'

**Comment by ngiger** [comment]
Ich vermute, dass man den Link aus http://www.spezialitätenliste.ch/ verwenden sollte, also http://www.xn--spezialittenliste-yqb.ch/File.axd?file=XMLPublications.zip.
Soll im Code der Link aus der HTML-Doku extrahiert werden oder der aktuelle Wert verwendet werden?

**Comment by zdavatz** [comment]
Verstehe Deine Frage nicht. Versuch es bitte mit dem Link `http://www.xn--spezialittenliste-yqb.ch/File.axd?file=XMLPublications.zip` - es muss einfach funktionieren.

**Comment by zdavatz** [comment]
siehe ecfe08ce0f1f0248691ebe59a56b430173aa059d

**Comment by ngiger** [comment]
Auf meinem Rechner lief der import_bsv_only ohne Probleme durch.
Das Problem liegt darin, dass auf thinpower in der Datei /var/www/oddb.org/etc/oddb.yml folgende Zeile zu finden ist:
`url_bag_sl_zip: "http://bag.e-mediat.net/SL2007.Web.External/File.axd?file=XMLPublications.zip"`
Die Datei etc/oddb.yml wurde am 7. Mai 2019 zum letzten Mal geändert.
Diese Zeile habe ich gelöscht und den job import_bsv gestartet. Der lief durch

**Comment by zdavatz** [comment]
Ok, Danke Dir!
